
const supOptions = ["ConsumerElectronics", "FashionAndAccessories", "Automotive", "FoodAndBeverages", "BabyCenter", "BeautyAndFragrances", "HomeGardenAndFurniture", "MachineryAndEquipment", "OfficeAndStationery", "PersonalCare", "PetAndAnimalCare", "SportsAndFitness", "Toys", "ToolsAndHomeImprovement"];

const subOptions = {
  ConsumerElectronics: ["AudioAndStudio", "CamerasAndCamcorders", "ComputersAndAccessories", "ElectricalAndElectronicAccessories", "GamingAndConsoles", "MobilePhonesAndTablets", "MusicalInstruments", "ProjectorsAndAccessories", "SmartHomeSolutions", "TelephonesAndCommunication", "TelevisionsAndStreamingDevices", "Wearables"],
  FashionAndAccessories: ["Bags", "Clothing", "Eyewear", "Footwear", "WatchesAndJewelry"],
  Automotive: ["AutomotiveCareAndCleaning", "AutomotivePartsAndAccessories", "GarageAndWorkshop", "OilsAndFluids", "RecoveryAndOffRoadAccessories", "WheelsTiresAndAccessories"],
  FoodAndBeverages: ["BakeryAndPastry", "Beverages", "Confectionery", "DairyAndEggs", "FrozenFood", "FruitAndVegetables", "MeatPoultryAndFish", "Pantry"],
  BabyCenter: ["BabyCare", "BabyClothingAndFootwear", "BabyDiapering", "BabyFeedingAndNursing", "BabyGear", "BabyNursery"],
  BeautyAndFragrances: ["BeautyTools", "Fragrances", "Makeup", "Nails", "Skincare"],
  HomeGardenAndFurniture: ["Appliances", "CommercialFurniture", "GardenAndOutdoor", "HomeDecor", "HomeFurniture", "HomeTextiles", "HouseholdSupplies", "KitchenAndDining"],
  MachineryAndEquipment: ["Printers3D", "AgriculturalMachineryEquipment", "ApparelAndTextileMachinery", "ChemicalAndPharmaceuticalMachinery", "CleaningAndFiltrationMachinery", "EngineeringAndConstructionMachinery", "FoodAndBeverageMachinery", "PackagingMachine", "PlasticAndRubberProcessingMachinery"],
  OfficeAndStationery: ["ArtAndCrafts", "BoardsAndEasels", "Books", "DeskSupplies", "FilesAndFolders", "GeneralSupplies", "OfficeFurniture", "OfficeMachinesAndEquipments", "PackagingMaterial", "PrintersScannersAndLabelMachines", "PrintingPaper", "TapesAndAdhesives", "TonersAndInkCartridges", "WritingInstruments", "WritingMaterial"],
  PersonalCare: ["Hair", "PersonalCare", "PersonalCareTools"],
  PetAndAnimalCare: ["AnimalFeedsAndSupplements", "PetAndAnimalsSupplies", "PetFood", "PetFurniture"],
  SportsAndFitness: ["FitnessAndTraining", "SportsAndOutdoorActivities", "WaterSportShoes", "WaterSportsAndActivities"],
  Toys: ["ArtsAndCrafts", "BabyToddlerToys", "BatteryOperatedToys", "ConstructionToys", "DollsAndDollhouses", "LearningAndEducational", "MusicalToys", "NoveltyToys", "OutdoorAndPlayground", "PlayFiguresAndVehicles", "PretendPlayAndCostumes", "PuzzlesAndGames"],
  ToolsAndHomeImprovement: ["BathroomAndKitchen", "Construction", "DoorsAndWindows", "ElectricalSupplies", "HomeImprovement", "Lighting", "SafetyAndSecurity", "TestMeasureAndInspect", "ToolsAndHardware"],
};

const miniSubOptions = {

  AudioAndStudio: ["AmplifiersAndSpeakers", "AudioAndVideoAccessories", "HeadphonesAndHeadsets", "MediaPlayers", "Radio", "RecordingAndStudioEquipment"],
  CamerasAndCamcorders: ["Camcorders", "CameraAccessories", "DigitalCameras", "InstantAndFilmCameras", "SecurityCamerasAndDrones", "WebcamsAndAccessories"],
  ComputersAndAccessories: ["ComputerAndLaptopComponents", "ComputerAccessories",  "KeyboardsAndKepads",  "Monitors", "Mouse", "NetworkAndSecurity", "PosSystems", "Softwares", 'StorageDevice'],
  ElectricalAndElectronicAccessories: ["Adapters", "CablesAndConnectors"],
  GamingAndConsoles: ["GamingAccessories", "GamingConsoles", "GamingTitles"],
  //problem 1
  MobilePhonesAndTablets: ["ChargersAndBatteries", "MobilePhoneAndTabletAccessories", "MobilePhones"],
  MusicalInstruments: ["KeyboardInstruments", "PercussionInstruments", 'StringedInstruments', "WindInstruments"],
  ProjectorsAndAccessories: ["ProjectorAccessories", "Projectors"],
  SmartHomeSolutions: ["SmartDevices", "SmartHomeDevices"],
  TelephonesAndCommunication: ["CommunicationAccessories", "Telephones"],
  TelevisionsAndStreamingDevices: ["DigitalDisplays", "HomeEntertainmentSystems", "StreamingDevices", "TvAccessories", "Televisions"],
  Wearables: ["FitnessTrackersAndAccessories", "SmartWatchesAndAccessories", "VirtualReality"],

  Bags: ["CasualBags", "FashionBags", "FormalBags", "Luggage", "SportBags", "TravelAccessories", "WalletsAndPurses"],
  Clothing: ["Accessories", "Beachwear", "Bottoms", "Costumes", "DressesAndKaftans", "FormalWear", "JacketsAndCoats", "JumpsuitsAndPlaysuits", "KidsAccessories", "KidsBottoms", "KidsJumpsuitsAndSets", "KidsSleepwear", "KidsSportswear", "kidsSwimwear", "KidsTops", "KidsUnderWear", "MaternityWear", "SleepWear", "SocksAndTights", "Sportswear", "Tops", "TraditionalWear", "UnderWear", "Uniforms"],
  Eyewear: ["ContactLenses", "Glasses", "GlassesAccessories"],
  Footwear: ["KidsShoes", "Shoes", "ShoesAccessories"],
  WatchesAndJewelry: ["JewelryAndAccessories", "Watches"],

  AutomotiveCareAndCleaning: ["AutomotiveCleaningTools", "ExteriorCare", "InteriorCare"],
  AutomotivePartsAndAccessories: ["ATVUTVPartsAndAccessories", "AviationPartsAndAccessories", "BusPartsAndAccessories", "CarBodyParts", "CarBrakeSystems", "CarElectricalSystems", "CarElectronics", "CarEngineSystems", "CarExhaustSystems", "CarExteriorAccessories", "CarHvacSystems", "CarInteriorAccessories", "CarLightingSystems", "CarSuspensionSystems", "CarTransmissionSystems", "ContainerAndTrailerPartsAndAccessories", "GoKartPartsAndAccessories", "HeavyDutyVehiclePartsAndAccessories", "MarinePartsAndAccessories", "MotorcycleAndScooterPartsAndAccessories", "NewEnergyVehiclePartsAndAccessories", "RVPartsAndAccessories", "TrainAndRailwayPartsAndAccessories", "TruckPartsAndAccessories"],
  GarageAndWorkshop: ["RepairEquipment"],
  OilsAndFluids: ["FluidFlushes", "GreasesAndLubricants", "Oils"],
  RecoveryAndOffRoadAccessories: ["EmergencyTools", "TowingAndWinches"],
  WheelsTiresAndAccessories: ["CommercialWheelsAndTires", "MotorcycleScooterWheelsAndTires", "PassengerCarAndOffRoadWheelsAndTires", "WheelPartsAndAccessories"],

  BakeryAndPastry: ["BreadAndWraps", "Pastry", "SweetsAndDelights"],
  Beverages: ["Coffee", "FitnessDrinks", "Juice", "ShakesAndSmoothies", "SoftDrinks", "Tea", "Water"],
  Confectionery: ["Chocolate", "CookiesAndBiscuits", "GumsAndMints"],
  DairyAndEggs: ["Butter", "Cheese", "Cream", "Eggs", "Milk", "YogurtAndLabneh"],
  FrozenFood: ["FrozenFishAndSeafood", "FrozenFruitsAndVegetables", "FrozenMealsAndAppentizers", "FrozenMeatAndPoultry", "FrozenSweetsAndDesserts"],
  FruitAndVegetables: ["FreshFruits", "FreshVegetables"],
  MeatPoultryAndFish: ["FishAndSeafood", "Meat", "Poultry"],
  Pantry: ["BakingDecorations", "BakingIngredients", "CannedFood", "Cereals", "DipsAndCondiments", "DryGroceryIndustrialIngredients", "GrainsAndPulses", "HoneyAndSyrups", "InstantFood", "JamsAndSpreads",  "OilsAndFats", "OlivesAndPickles", "Snacks", "SpicesAndSeasonings", "Stock", "SugarAndSugarAlternatives"],

  BabyCare: ["BabyBath", "BabyHealthCareAndGrooming", "BabySafety", "BabySkinCare"],
  BabyClothingAndFootwear: ["BabyClothing", "BabyClothingAccessories", "BabyFootwear"],
  BabyDiapering: ["BabyDiapers", "ChangingPads", "DiaperingAccessories", "PottyTraining"],
  BabyFeedingAndNursing: ["BabyFeeding", "BabyFood", "BibsAndBurpCloths", "BottleFeeding", "Breastfeeding", "PacifiersAndTeethers"],
  BabyGear: ["Activity", "ChairsAndSeats", "StrollersAndCarSeats", "Travel"],
  BabyNursery: ["BabyBeddings", "BabyFurniture"],

  BeautyTools: ["MakeupToolsAndAccessories", "NailCareTools", "SkincareTools"],
  Fragrances: ["Perfumes"],
  Makeup: ["BodyArt", "BodyMakeup", "EyeMakeup", "EyebrowMakeup", "FaceMakeup", "Lips"],
  Nails: ["NailArt", "NailCareProducts"],
  Skincare: ["EyeCare", "FaceCare", "LipCare", "SunCareAndTanning"],

  Appliances: ["CleaningAppliances", "CoffeeAndEspressoMachines", "CollingAppliances", "HeatingAppliances", "LargeKitchenApliances", "LaundaryAppliances", "SmallKitchenAppliances"],
  CommercialFurniture: ["BarFurniture", "HairSalonFurniture", "HealthAndMedicalFurniture", "HotelFurniture", "RestaurantFurniture", "SchoolFurniture"],
  GardenAndOutdoor: ["BBQAndGrills", "GardenDecor", "GardeningTools", "OutdoorFurniture", "PestControl", "WateringAndIrrigation"],
  HomeDecor: ["ArtworkAndFrames", "Clocks", "DecorativeAccessories", "HomeFragrances", "Islamic", "Mirrors", "PartySupplies"],
  HomeFurniture: ["Bedrooms", "DiningRooms", "KidsAndBabyFurniture", "KitchenFurniture", "LivingRooms"],
  HomeTextiles: ["Bedding", "CarpetsAndRugs", "CurtainsAndBlinds"],
  HouseholdSupplies: ["BathroomAccessories", "CleaningSupplies", "CleaningTools", "DisposableHygieneProducts", "DisposableTableware", "HomeStorageAndOrganization", "KitchenEssentials", "KitchenLines", "KitchenStorageAndOrganisation", "LaundryStorageAndOrganization", "PhotoAlbums", "SewingAndAccessories", "StorageAndOrganization", "TableEssentials"],
  KitchenAndDining: ["Bakeware", "CoffeeAndTeaTools", "Cookware", "Dinnerware", "Drinkware", "KitchenKnivesAndAccessories", "KitchenToolsAndUtensils", "Tableware"],

  Printers3D: ["Printers3D"],
  //problem 2
  AgriculturalMachineryEquipment: ["AgriculturalMachineryParts", "AgriculturalSprayer", "AnimalAndPoultryHusbandrEquipment", "AquacultureMachineAerators", "Balers", "BiomassBriquetteMachines", "BiomassDryers", "CompostMakingMachines", "Cultivators", "EggIncubators", "FarmIrrigationSystem", "FarmTrailer", "FeedProcessingMachines", "FertilizerSpreaders", "ForestryMachinery", "Harvesters", "IndoorFarmingAndHydroponicsMachines", "IrrigationEquipment", "MilkingMachines", "OilPressers", "OtherAgriculturalMachineryAndEquipments", "OtherFarmMachines", "SeedProcessingMachines", "Seeders", "Shellers", "Silos", "SlaughteringEquipment", "TowableBachoe", "Tractors"],
  ApparelAndTextileMachinery: ["ApparelAndTextileMachineryParts", "ApparelMachinery", "CapMakingMachines", "HomeTextileProduct", "IroningAndWashingEquipments", "LeatherProductionMachinery", "ShoeMakingMachines", "TextileMachinery"],
  ChemicalAndPharmaceuticalMachinery: ["ChemicalMachineryAndEquipment", "CosmeticsProductionEquipment", "Crystalizer", "PharmaceuticalMachinery"],
  CleaningAndFiltrationMachinery: ["AirCleaningEquipment", "CleaningEquipmentParts", "CornerCleaningMachines", "DishwashingEquipments", "FiltrationEquipment"],
   //problem 3
  EngineeringAndConstructionMachinery: ["AbrasiveMachines", "BuildingMaterialMachinery", "ConcreteMachinery", "ConstructionLifter", "ConstructionMachinery", "Cranes", "CuttingMachines", "DrillingMachines", "EarthMovingMachines", "ElectronicsProductionsMachinery", "GaugesIndicatorsAndMeter", "MortarSprayMachines", "MunicipalMachinery", "OtherConstructionMachinery", "PileDriver", "PipeJackingMachines", "PolishingMachines", "Rammers", "RenderingMachines", "RoadMachinery", "ScientificLabEquipment"],
  FoodAndBeverageMachinery: [ "BakingEquipment", "BeanProductProcessingMachinery", "BeverageProcessingMachines", "CoffeeMachine", "DairyProcessingMachine",  "FoodProcessingMachines", "FoodSterlizer", "FruitAndVegetableProcessingMachines", "Fryer", "GrainProcessingMachines", "GrainProductMakingMachines", "HoneyProcessingMachines", "KitchenMachines", "MeatProcessingMachine", "MeatProductionMakingMachines", "NutsProcessingMachines", "OtherFoodProcessing", "Pasteurizer", "PetFoodProcessingMachines", "SeasoningProcessing", "SnackMacine"],
  PackagingMachine: ["AuxiliaryPackagingMachines", "BlisterPackahingMachines", "BoxingMachine", "CappingMachines", "CoatingMachines", "EmbossingMachines", "FillingMachines", "GluingMachines", "LabelingMachines", "LaminatingMachines", "MultiFunctionPackagingMachines", "OtherPackaginMachines", "PackagingFormingMachines", "PackagingLine", "PackagingMachinery", "PackagingMateialMachines", "SealingMachines", "VacuumPackagingMachines", "WrappingMachines"],
  PlasticAndRubberProcessingMachinery: ["FoamCuttingMachine", "FoamMachinery", "InjectionMoldingMachines", "OtherPlasticProductMakingMachinery", "OtherPlasticAndRubberMachinery", "PipeBellingMachines", "PlasticAndRubberMachinery", "PlasticAuxiliaryEquipment", "PlasticBowlingMachinery", "PlasticCuttingMachinery", "PlasticExtruders", "PlasticFlockingMachinery", "PlasticLaminatingMachinery", "PlasticRawMaterialMachinery", "PlasticRecyclingMachinery", "PlasticRotationalMoldingMachines", "PlasticThermoformingMachines", "RubberPRocessingMachines", "RubberProductMakingMachines", "RubberRecyclingMach"],

  ArtAndCrafts: ["ArtAndCraftPaper", "ArtAndCraftSets", "BeadsSequinsAndGlitter", "CanvasAndArtPads", "CraftAccessories", "CuttingTools", "GlueGunsAndSticks", "MeasuringTools", "PaintAndColors", "PaintBrushes", "Palettes", "SewingTools", "YarnAndThreads"],
  BoardsAndEasels: ["BoardAccessories", "BulletinBoards", "ChalkBoards", "EaselsAndEaselPads", "GlassBoards", "WhiteBoards"],
  Books: ["BookReaders", "ChildrensBooks", "Fiction", "NonFiction"],
  DeskSupplies: ["BinsAndBaskets", "BusinessCardsAndOrganizers", "DeskOrganizersAndAccessories", "DocumentTraysAndDrawing", "PenMemoAndClipHolders"],
  FilesAndFolders: ["DividersAndBookmarks", "DocumentBagsAndDisplayBooks", "FileStorage", "HangingAndExpandingFiles", "LaminatingFilms", "LeverArchAndBoxFiles", "RingBindersAndViewBinder", "SuspensionAndReportFiles"],
  GeneralSupplies: ["Batteries", "BinderClipsAndPins", "Clipboards", "Envelopes", "GeneralAccessories", "KeyBoxAndAccessories", "NameBadgesAndLanyari", "Punchers", "RubberBands", "Rulers", "Scissors", "SignsLabelsAndStickers", "StampsAndSeals", "StaplesAndStaplers"],
  OfficeFurniture: ["CabinetsAndDrawerUnits", "ChairsAndSeating", "OfficeDesksAndTables"],
  OfficeMachinesAndEquipments: ["AttendanceMachines", "BindingMachines", "Calculators", "CashHandlingMachines", "Laminators", "PaperTrimmers&Cutt", "Safes", "Shredders"],
  PackagingMaterial: ["GiftBagsBoxesAndWraps", "PackagingPaperAndWraps", "PackagingPouchAndBox"],
  PrintersScannersAndLabelMachines: ["AddressLabels", "BarcodeLabels", "DotMatrixPrinters", "IdCardPrinters", "InkJetPrinters", "LabelMakers", "LaserJetPrinter", "PrintersAndScannersAccessories", "Scanners", "ShippingLabels"],
  PrintingPaper: ["ColorPaper", "CopyPaper", "PaperRolls", "SpecialtyPaper"],
  TapesAndAdhesives: ["DuctTapes", "GluesAndAdhesives", "MaskingTapes", "PackingTapes", "SpecialtyTapes", "TapeDispensers", "TransparentTapes"],
  TonersAndInkCartridges: ["InkCartridges", "TonersCartridges"],
  WritingInstruments: ["CorrectionPensAndFluids", "GeometryAndScienceSupplies", "MarkersAndHighlighter", "PencilsAndLead", "Pens", "SharpencersAndErasers", "WritingAccessories"],
  WritingMaterial: ["AddressAndAccountingBooks", "CalendarJournalAndDiaries", "NotebooksAndWritingPads", "StickyNotesAndNoteCards"],

  Hair: ["HairAccessories", "HairCare", "HairColoring", "HairStylingProducts"],
  PersonalCare: ["BathAndBody", "HairSalonDisposables", "MassageAndRelaxation", "OralAndDentalCare", "ShavingAndHairRemovalProducts", ""],
  PersonalCareTools: ["HairStylingTools", "ShavingAndHairRemovalTools"],

  AnimalFeedsAndSupplements: ["AnimalFeedsAndSupplements", ""],
  PetAndAnimalsSupplies: ["CleaningSupplies", "CollarsAndLeashes", "FeedingAndWateringSupplies", "GroomingSupplies", "HealthSupplies", "PetApparelAndAccessories", "PetHeatLamps", "Toys", "TrainingAndBehaviorSupplies"],
  PetFood: ["Chews", "DryFoods", "Milk", "Treats", "WetFoods"],
  PetFurniture: ["Aquariums", "Beds", "Crates", "Gages"],

  FitnessAndTraining: ["ExerciseMachines", "FitnessAccessories", "WeightAndResistanceTraining"],
  SportsAndOutdoorActivities: ["BallGames", "BikePartsAndTools", "BikesAndElectricBikes", "BoxingRings", "CampingAccessories", "CampingPersonalCare", "CampingTables,Chair", "Fishing", "OutdoorCookingAndEating", "OutdoorRecreation", "PunshingBagsAndSpeed", "RacketSports", "ScootersAndHoverBoards", "Skates", "SleepingBagsAndBedding", "SporsProtectiveGear", "TentsAndCanopies"],
  WaterSportShoes: ["WaterSportShoes"],
  WaterSportsAndActivities: ["WaterSportsAndActivities"],

  ArtsAndCrafts: ["AdventCalendars", "CraftSets", "DrawAndPaint", "PlayDoughAndClay", "SandAndMoulds"],
  BabyToddlerToys: ["BabyGymsAndPlaymats", "BabyToys", "BathToys", "EarlyLearning", "FloorMats"],
  BatteryOperatedToys: ["RemoteControlToys"],
  ConstructionToys: ["BuildingBlocks", "BuildingToys"],
  DollsAndDollhouses: ["DollhousesAndAccessories", "Dolls"],
  LearningAndEducational: ["LanguageAndLiteracy", "MathAndCountToys", "ScienceToys", "WritingBoards"],
  MusicalToys: ["SoundAndLightToys"],
  NoveltyToys: ["FidgetToys", "SquishyToys"],
  OutdoorAndPlayground: ["BeachToys", "BikesScootersAndRideOns", "OutDoorPlay", "PlayGroundSet", "PoolsAndWaterFun"],
  PlayFiguresAndVehicles: ["AnimalAndActionFigures", "VehicleToys"],
  PretendPlayAndCostumes: ["DressingUpAndCostumes", "PretendPlay", ""],
  PuzzlesAndGames: ["Games", "Puzzles"],

  BathroomAndKitchen: ["BathroomAndKitchenAccessories", "SinksVanitiesAndCabinets", "BathroomAndKitchenAccessories", 'SinksVanitiesAndCabinets', "TapsAndFaucets", "ToiletsAndAcessories", "Tubs&Showers"],
  Construction: ["BuildingBoards", "BuildingGlassAndAccessories", "BuildingMaterial", "Ceiling", "ElevatorsAndEscalator", "Flooring", "handrailsAndBalustrad", "LaddersAndScaffolding"],
  DoorsAndWindows: ["DoorAndWindowHardware", "Doors", "Windows"],
  ElectricalSupplies: ["CablesWiresAndAccessories", "FusesAndCircuitBreakers", "PlugsAndSockets", "PowerSupplies", "RelaysAndControllers", "Sitches", "TerminalsAndConnectors"],
  HomeImprovement: ["AdhesivesAndFillers", "PaintAndCoating", "PaintAndCoating"],
  Lighting: ["IndoorLighting", "OutdoorLighting", 'PortableLighting'],
  SafetyAndSecurity: ["Alarms", "ChildSafety", "Firefighting", "LocksAndKeys", "RoadwaySafety", "Surveillance", "WaterSafety", "WorkplaceSafety"],
  TestMeasureAndInspect: ["DimensionalAndLevelMeasurement", "ElectricalMeasurement", "EmissionMesurement", "FlowMeasurement", "LabSupplies", "MotionForceAndSpeed", "NetworkAndCableTesting", "PressureMeasurement", "SoundAndLightMeasurment", "TemperatureAndHumidityMeasurement", "WaterAndFoodTesting", "WeightMeasurement"],
  ToolsAndHardware: ["Fasteners", "FurnitureHardware", "HandTools", "HydraulicTools", "PowerTools", "ToolORganizers", "ToolParts", "ValvesPumpsAndPlumbing"],

};

const microSubOptions = {

  AmplifiersAndSpeakers: ["Amplifiers", "Boomboxes", "CeilingSpeakers", "ComputerSpeakers", "FloorStandSpeakers", "Loudspeakers", "MonitorSpeakers", "OutdoorSpeakers", "PortableSpeakers", "SoundbarSpeakers", "Subwoofers", "WallMountSpeakers"],
  AudioAndVideoAccessories: ["AudioAndVideoSplitters", "AudioConverters", "AudioFiltersAndEqualizers", "AudioInterfaces", "AudioMixers", "MountsAndHolders", "SpeakerMountsAndStands", "VideoConverters", "VideoSwitchers"],
  HeadphonesAndHeadsets: ["HeadphoneAccessories", "Headphones", "Headsets", "WirelessEarbuds"],
  MediaPlayers: ["BluRayPlayers", "CDPlayersAndRecorders", "DVDPlayersAndRecorders", "MP3AndMP4Players", "StereoSystems", "TurntablesAndRecordPlayers"],
  Radio: ["AnalogRadios", "ClockRadios", "DigitalRadios"],
  RecordingAndStudioEquipment: ["KaraokeSystems", "MicrophoneCovers", "MicrophoneFilters", "Microphones", "VoiceRecorders"],

  Camcorders: ["DVDCamcorders", "FlashMemoryCamcorders", "HDDCamcorders", "Mini-DVCamcorders"],
  CameraAccessories: ["AccessoriesSets", "CameraBagsCoversAndCases", "CameraChargersAndBatteries", "CameraFilms", "CameraFiltersAndProtectors", "CameraLenses", "CameraStrapsHolders", "ClapperBoards", "DigitalPhotoFrames", "FlashesAndLighting", "Gimbals", "LensCapsAndHoods", "LensCleaningKits", "Sliders", "StudioBackgrounds", "TripodsAndMonopods"],
  DigitalCameras: ["360-DegreeCameras", "Action Cameras", "CompactDigitalCameras", "DSLRCameras", "MirrorlessCameras"],
  InstantAndFilmCameras: ["FilmCameras", "InstantCameras"],
  SecurityCamerasAndDrones: ["BinocularsAndTelescopes", "Drones", "SecurityCameras", "SurveillanceSystems"],
  WebcamsAndAccessories: ["WebcamCovers", "Webcams"],

  ComputerAndLaptopComponents: ["CPUsAndProcessors", "ComputerFans", "GraphicCards", "MotherBoards", "RamsAndRoms", "SoundCards"],
  ComputerAccessories: ["CDsAndDVDsCases", "CardReadersAndWriters", "ComputerAndLaptopCleaning", "ComputerAdapters", "ComputerCables", "ComputerCases", "DesktopPowerCables", "HardDriveEnclosure", "KvmSwitches", "NetworkAdapters", "PowerSupplies", "ScreenFiltersAndProtectors", "UsbAdapters"],
  DextopComputers: ["AllInOneComputers", "DextopLaptops", "GamingLaptops", "MiniPcs", "Workstations"],
  KeyboardsAndKepads: ["GamingKeyboards", "KeyboardCover", "Keypads"],
  LaptopAndNotebookAccessories: ["Lapdesks", "LaptopBagsAndBackpack", "LaptopChargersAndBattries", "LaptopCoolingPads", "LaptopCoversAndCases", "LaptopLights", "LaptopLocks", "LaptopStandsAndMounts", "NotebookCoversAndCases"],
  LaptopsAndNoteBooks: ["GamingLaptops", "MobileWorkstations", "Notebooks", "RuggedLaptops"],
  Monitors: ["ComputerMonitors", "GamingMonitors"],
  Mouse: ["ComputerMouse", "MousePadsAndCases"],
  NetworkAndSecurity: ["AccessPoints", "DockingStations", "EthernetSwitches", "FirewallsAndVpn", "Modems", "NetworkBridges", "NetworkCabinets", "NetworkGatways", "NetworkHubs", "NetworkInterfaceCards", "NetwrokSwitches", "NetworkTransceivers"],
  PosSystems: ["CashRegisterDrawers", "CashRegisters", "CreditCardReaders", "MobileComputers", "PosComputerSystem", "PosEquipmentOther", "PoleDisplays", "PosComputersAndAccessories"],
  Softwares: ["AccountingAndFinance", "AntivirusAndSecurity", "BusinessAndOffice", "DesignAndIllustration", "EducationAndReferences", "OperatingSystems", "PhotoVideoAndMusic", "TestingAndEngineering", "Utilities"],
  StorageDevice: ["CdsAndDvds", "ExternalHardDiskDrive", "ExternalSolidStateDrives", "FlashDrives", "GamingDrives", "InternalHardDiskDrives", "InternalSolidStateDevies", "MemoryCards", "NetworkAttachedStorage"],

  Adapters: ["CableAdapters", "PowerAdapters"],
  CablesAndConnectors: ["AUXCables", "AudioCables", "CableAccessories", "CoaxialCables", "ElectricalConnector", "EthernetCables", "HdmiCables", "PowerExtensionCords", "RcaCables", "SurgeProtectors"],

  GamingAccessories: ["BatteriesAndChargers", "GameCaptureCards", "GameConsoleBags", "GamingChairs", "GamingFingerSleeves", "GamingHeadsets", "GamingJoysticks", "GamingMouse", "GamingStandsAndHold", "GamingTriggers", "RacingWheels"],
  GamingConsoles: ["Nintendo", "Playstation", "XBox"],
  GamingTitles: ["PcAndVideoGames"],

  ChargersAndBatteries: ["CarChargers", "ChargingCables", "MobilePhonesAndTablet", "PowerBanks", "WallChargers", "WirelessChargers"],
  MobilePhoneAndTabletAccessories: ["ArmBands", "CoversAndCases", "FlashesAndLights", "GripsAndHolders", "ItemFindersAndAccessories", "LanyardsAndWristStraps", "LensAccessories", "LightsAndFlashes", "MicroSdCards", "MobileParts", "MobilePhonesControl", "MountsAndStands", "ScreenProtectors", "SelfieSticks", "StylusPensAndCovers"],
  MobilePhones: ["CellPhones", "SmartPhones"],
  //problem 1
  TabletsAndEBooksReaders: ["EbookReaders", "Tablets"],


  KeyboardInstruments: ["Accordion", "ElectricOrgan", "Electric", "KeyboardInstrument", "Piano"],
  PercussionInstruments: ["Castanets", "ChimesAndTriangles", "Cymbals", "Drum", "Gong", "Maracas", "PercussionInstruments", "Tambourine", "Xylophone"],
  StringedInstruments: ["Banjo", "Bouzouki", "Cello", "ElectricGuitar", "Guitar", "Harp", "HurdyGurdy", "Lute", "Mandolin", "Oud", "StringedInstrumentsPartsAndAccessories", "Violin", "Zither"],
  WindInstruments: ["Basson", "Clarinet", "Flute", "Harmonica", "Horm", "Melodica", "Oboe", "PanFlute", "Recorder", "Saxophone", "Trombone", "Trumpet", "Tuba", "WindInstrumentsPartsAndAccessories"],

  ProjectorAccessories: ["PresentationPointers", "ProjectorAirFilters", "ProjectorBagsAndCases", "ProjectorLamps", "ProjectorMountsAndStands", "ProjectorRemoteControls", "ProjectorScreens"],
  Projectors: ["DLPProjectors", "LCDProjectors", "LedProjectors", "MiniProjectors", "MovieProjectors"],

  SmartDevices: ["SmartDevices"],
  SmartHomeDevices: ["SmartDisplays", "SmartLights", "SmartSecuritySystems", "SmartSensors", "SmartSpeakers"],

  CommunicationAccessories: ["CordlessPhoneBatteries", "LandlineHeadsets", "PhoneCables", "PhoneCords", "PhoneSplitters"],
  Telephones: ["CallerIDTelephones", "CordedTelephones", "CordlessTelephones", "DigitalAnsweringMachines", "PabxTelephones", "TwoWayRadios", "VoipTelephones"],

  DigitalDisplays: ["DigitalSignage", "InteractiveDisplays"],
  HomeEntertainmentSystems: ["HiFiSystems", "HomeTheaterSystems"],
  StreamingDevices: ['SatelliteReceivers', "TvBoxes", "TvTuners"],
  TvAccessories: ["TvMounts", "TvRemoteControls"],
  Televisions: ["Lcd", "Led", "PlasmaScreens"],

  FitnessTrackersAndAccessories: ["FitnessTrackerBands", "FitnessTrackerChargers"],
  SmartWatchesAndAccessories: ["SmartWatchAccessories", "SmartWatchBands"],
  VirtualReality: ["3dGlasses", "VirtualRealityAccessories", "VirtualRealityHeadsets"],

  CasualBags: ["BagAccessories", "SchoolBagsAndBackpacks", "ShoppingBags", "SpecialtyBagsAndBackpacks"],
  FashionBags: ["BeltBags", "CrossbodyBags", "FashionBackpacks", "HandbagsAndSets", "ShoulderBags"],
  FormalBags: ["Briefcase", "MessangerBags"],
  Luggage: ["LuggageSets", "TravelBagsAndsuitcase"],
  SportBags: ["SportBagsandBackpacks", "SportWaistBags"],
  TravelAccessories: ["GarmentBags", "LuggageCovers", "LuggageLocks", "LuggageScales", "LuggageTags", "PackingOrganizes", "PassportCovers", "TravelDocumentHolders", "Umbrellas"],
  WalletsAndPurses: ["CardCases", "ChequeBookCovers", "CoinPurses", "Wallets"],


  Accessories: ["BeltsAndSuspenders", "BowsAndTies", "BroochesAndPins", "Buttons", "Gloves", "HatsAndCaps", "PocketSquares", "ScarvesAndWraps"],
  Beachwear: ["BeachDresses", "Bikinis", "SwimBriefs", "SwimCaps", "SwimDresses", "SwimShorts", "Swimsuits"],
  Bottoms: ["Jeans", "PantsAndLeggings", "Sports", "Skirts"],
  Costumes: ["Animals", "Bugs", "Characters", "FairytaleAndStorybooks", "HorrorAndGothic", "MoviesAndVideoGames", "PlantsAndFood", "Superhero"],
  DressesAndKaftans: ["Dresses", "Kaftans"],
  FormalWear: ["Suits", "Tuxedos"],
  JacketsAndCoats: ["Blazer", "Coats", "Jackets"],
  JumpsuitsAndPlaysuits: ["Jumpsuits", "Playsuits"],
  KidsAccessories: ["KidsBeltsAndSuspenders", "KidsGlovesAndScarves", "KidsHatAndCaps", "KidsPursesAndWallets", "KidsSocksAndTights", "KidsSunglasses", "KidsWatchesAndJewellery"],
  KidsBottoms: ["KidsJeans", "KidsPantsAndLeggings", "KidsShorts", "KidsSkirts"],
  KidsJumpsuitsAndSets: ["KidsCostumes", "KidsJumpsuitsAndRompers", "KidsSets", "KidsSuitsAndTuxedos"],
  KidsSleepwear: ["KidsNightDresses", "KidsNightwearSets", "KidsPajamas", "KidsRobes", "KidsSleepingMasks"],
  KidsSportswear: ["KidsSportBottoms", "KidsSportTops", "KidsTracksuitsAndSets"],
  kidsSwimwear: ["KidsBikinis", "kidsSwimBriefs", "kidsSwimCaps", "kidsSwimDresses", "kidsSwimShorts", "kidsSwimsuits"],
  KidsTops: ["KidsDresses", "KidsJacketsAndCoats", "KidsShirtsAndBlouses", "KidsSweatshirtsAndKnitwear"],
  KidsUnderWear: ["KidsBodysuits", "KidsBoxersAndBriefs", "KidsUndershirts"],
  MaternityWear: ["MaternityBottom", "MaternityDresses", "MaternityJumpsuits", "MaternitySleepwear", "MaternitySupports", "MaternityTops", "MaternityUnderwear"],
  SleepWear: ["Lingerie", "NightDressesAndGowns", "NightWearSets", "Pajamas", "Robes", "SleepMasks"],
  SocksAndTights: ["SocksAndStockings", "Tights"],
  Sportswear: ["SportBottoms", "SportGlovesAndHandwraps", "SportSocks", "SportTops", "SportTrackSuitsAndSets", "SportUnderwear"],
  Tops: ["ShirtsAndBlouses", "SweatshirtsAndKnitwear", "TShirtsAndPolo", "Vests"],
  TraditionalWear: ["AfricanWear", "ArabicAndIslamicWear", "EuropeanWear", "IndianAndPakistaniWear"],
  UnderWear: ["Boxers,BriefsAndPanties", "BraAccessories", "Bras", "ShapewearAndBodysuits", "Undershirts"],
  Uniforms: ["ChefsUniforms", "DomesticWorkerUniforms", "MedicalUniforms", "ScoutingUniforms"],


  ContactLenses: ["ColoredContactLenses", "ContactLensesSolutions", "CorrectiveContactLenses"],
  Glasses: ["EyeglassesFrames", "ReadingGlasses", "Sunglasses"],
  GlassesAccessories: ["GlassesCases", "GlassesChains", "GlassesCleaningTools"],

  KidsShoes: ["KidsBoots", "KidsFlats", "KidsSandals", "KidsSlippers", "KidsSportShoes"],
  Shoes: ["Boots", "CasualShoes", "Flats", "FormalShoes", "Heels", "SandalsAndFloaters", "SlippersAndFlipFlops", "SportShoes"],
  ShoesAccessories: ["Insoles", "ShoeBagsAndCovers", "ShoeBrushes", "ShoePolish", "Shoehorns", "Shoelaces"],

  JewelryAndAccessories: ["Anklets", "Bracelets", "Cufflinks", "DisplayHeadStands", "Earrings", "JewelleryBoxes", "JewellerySets", "Keychains", "LooseGemstonesAndDiamonds", "MoneyClip", "Necklaces", "PendantsAndCharms", "Piercings", "Rings", "Rosaries", "TieBar"],
  Watches: ["AnalogWatches", "AnalogDigitalWatches", "DigitalWatches", "WatchAccessories"],

  AutomotiveCleaningTools: ["Applicators", "CleaningToolsAndKits"],
  ExteriorCare: ["AutomotiveGlassCare", "AutomotivePolishesAndWaxes", "AutomotiveProtectiveSprays", "AutomotiveRustRemovers", "AutomotiveWashAndCleaners"],
  InteriorCare: ["AutomotiveFresheners", "AutomotiveLeatherCare", "AutomotiveUpholsteryCare"],

  ATVUTVPartsAndAccessories: ["ATVUTVAccessories", "ATVUTVParts"],
  AviationPartsAndAccessories: ["AviationAccessories", "AviationParts"],
  BusPartsAndAccessories: ["BusBodyKits", "BusBrakes", "BusEngines", "BusGrabHandles", "BusLights", "BusSeats"],
  CarBodyParts: ["CarBumpers", "CarDashboards", "CarDoors", "CarFenders", "CarGearKnobs", "CarMirrors", "CarPedals", "CarSteeringWheels", "CarWindows", "SeatsAndSeatBelts", "Windshield"],
  CarBrakeSystems: ["AutoBrakeCables", "Brakes", "Handbrakes"],
  CarElectricalSystems: ["AutoMeters", "AutoSwitches", "CarBatteries", "CarHornsAndSpeakers"],
  CarElectronics: ["CarBlackBox", "CarDVDPlayer", "CarDashcams", "CarDisplays", "CarMonitors", "CarRadio", "CarReversingAid", "GPSTrackers", "VehicleKeys"],
  CarEngineSystems: ["CarEngines", "CarburetorsAndThrottles", "Filters", "IgnitionCables", "IgnitionCoils", "InjectionValves", "Radiators", "SparkPlugs", "TurbochargersAndSuperchargers"],
  CarExhaustSystems: ["CatalyticConverters", "ExhaustManifolds", "ExhaustPipes", "Mufflers", "OxygenSensors", "Resonators", "TailPipes"],
  CarExteriorAccessories: ["CarAntennas", "CarCovers", "CarDeflectors", "CarFilms", "CarRoofBoxes", "CarRoofRacks", "CarStickers", "DoorHandles", "RunningBoards", "WindshieldWipers"],
  CarHvacSystems: ["ACCompressors", "ACControl", "AirHoses", "AirVentilation", "BlowerFans", "Condensers", "Evaporators", "HeaterCores", "Thermostats"],
  CarInteriorAccessories: ["CarClothesHangers", "CarCupHolders", "CarDecoration", "CarKeyAccessories", "CarKickPanels", "CarLocks", "CarMats", "CarOrganizers", "CarSunshades", "CarTrashCans", "CenterConsolesAndArmrests", "SeatCovers", "SeatCushionsAndPillows", "SteeringWheelCovers"],
  CarLightingSystems: ["AutoFogLights", "AutoHeadlights", "AutoInteriorLights", "AutoLightBulbs", "AutoTailLights",],
  CarSuspensionSystems: ["BallJoints", "Bearings", "ControlArms", "RubberMountings", "ShockAbsorberSprings", "ShockAbsorbers", "StabilizerLinks", "SuspensionStruts"],
  CarTransmissionSystems: ["ClutchMasterCylinders", "Driveshafts", "Gearboxes", "PropellerShafts", "TensionersAndBelts"],
  ContainerAndTrailerPartsAndAccessories: ["ContainerPartsAndAccessories", "TrailerPartsAndAccessories"],
  GoKartPartsAndAccessories: ["GoKartBodyParts", "GoKartBrakeSystems", "GoKartCabinCovers", "GoKartEngines", "GoKartHardware", "GoKartModificationAccessories", "GoKartSeats", "GoKartSteeringWheels"],
  HeavyDutyVehiclePartsAndAccessories: ["HeavyDutyVehicleAccessories"],
  MarinePartsAndAccessories: ["BoatAnchors", "BoatCovers", "BoatEngines", "MarineHardware", "MarinePropellers", "MarinePumps"],
  MotorcycleAndScooterPartsAndAccessories: ["MotorcycleAndScooterAccessories", "MotorcycleAndScooterBodyParts", "MotorcycleAndScooterBrakes", "MotorcycleAndScooterEngines", "MotorcycleAndScooterGauges", "MotorcycleAndScooterHandlebarsAndControls", "MotorcycleAndScooterLights", "MotorcycleAndScooterProtectiveGear", "MotorcycleAndScooterRacks", "MotorcycleAndScooterSeats", "MotorcycleAndScooterSuspensionSystems"],
  NewEnergyVehiclePartsAndAccessories: ["DC/DCConverters", "EVChargingCableHolders", "EVChargingCables", "EVChargingStations", "EVConnectors", "ElectricMotors", "OnBoardChargers"],
  RVPartsAndAccessories: ["RVAttachedTents", "RVAwningScreensAndAccessories", "RVCookingAppliances", "RVCovers", "RVDrainSystems", "RVExternalShowerSystems", "RVFittingsAndAssemblyParts", "RVToilets"],
  TrainAndRailwayPartsAndAccessories: ["RailwayPartsAndAccessories", "TrainPartsAndAccessories"],
  TruckPartsAndAccessories: ["TruckBearings", "TruckBodyParts", "TruckBrakeDiscs", "TruckBrakePads", "TruckBrakeShoes", "TruckBrakeSystems", "TruckEngineParts", "TruckExhaustSystems", "TruckFasteners", "TruckLights", "TruckRepairKits", "TruckSealingKits", "TruckSteeringParts", "TruckTransmissions"],

  RepairEquipment: ["BodyRepairTools", "CreepersAndRollerSeats", "DiagnosticTools", "ParkingEquipment", "TireChangers", "TireInflators", "TireRepairTools", "VehicleLifts", "WheelAlignmentMachines"],

  FluidFlushes: ["AutomaticTransmissionFluids", "BrakeFluids", "CarburetorAndThrottleBodyCleaners", "EngineCleaners", "EngineCoolants", "FluidAdditives", "FuelInjectionFluids", "FuelSystemCleaners", "PowerSteeringFluids", "RadiatorFluids", "WindshieldWiperFluids"],
  GreasesAndLubricants: ["GreaseAdditives", "Greases", "LubricantAdditives", "Lubricants"],
  Oils: ["AirConditioningOils", "EngineOils", "GearOils", "HydraulicOils", "OilAdditives"],

  EmergencyTools: ["CarEmergencyEquipment", "JerryCans", "JumpStarters"],
  TowingAndWinches: ["HitchHooks", "HitchMounts", "TowBalls", "TowBars", "TowHooks", "TowRopes"],

  CommercialWheelsAndTires: ["RVTires", "RVWheels", "TrailerTires", "TrailerWheels", "TruckTires", "TruckWheels"],
  MotorcycleScooterWheelsAndTires: ["MotorcycleTires", "MotorcycleWheels", "ScooterTires", "ScooterWheels"],
  PassengerCarAndOffRoadWheelsAndTires: ["ATVAndUTVTires", "ATVAndUTVWheels", "CarTires", "CarWheels", "PickupAndSUVTires", "PickupAndSUVWheels", "RacingCarTires", "RacingCarWheels"],
  WheelPartsAndAccessories: ["LugNutsAndAccessories", "SnowChains", "ValveStemsCapsAndAdapters", "WheelCaps", "WheelDustShields", "WheelHubsAdaptersAndSpacers", "WheelParts", "WheelWeights"],

  BreadAndWraps: ["BunsAndRolls", "Flatbread", "LoafBread", "SlicedBread", "Specialtybread", "TortillaAndWraps"],
  Pastry: ["CakesAndMuffins", "KaakAndBreadsticks", "PastriesAndManakish", "PuffsAndCroissants", "TartsAndPies"],
  SweetsAndDelights: ["ArabicSweetsAndDesserts", "CoatedDatesAndNuts", "IndianDesserts", "Mamoul", "TurkishDelights"],

  Coffee: ["ArabicCoffee", "CapsulesAndPods", "CoffeeAlternatives", "CoffeeBeans", "CoffeeCreamers", "DecafCoffee", "GroundCoffee", "InstantCoffee", "SpecialtyCoffee", "TurkishCoffee"],
  FitnessDrinks: ["ProteinDrinks", "ShotsAndBoosters"],
  Juice: ["FreshJuice", "FruitJuice", "JuiceConcentrates", "VegetableJuice"],
  ShakesAndSmoothies: ["Shakes", "Smoothies"],
  SoftDrinks: ['CarbonatedDrinks', "EnergyDrinks", "IceCoffeeAndIceTea", "InstantDrinkPowder"],
  Tea: ["BlackTea", "DecafTea", "FlavoredTea", "GreenTea", "HealthAndWellness", "HerbalTea", "KarakTea", "WhiteTea"],
  Water: ["FlavoredWater", "SparklingWater", "StillWater", "VitaminFortifiedWater"],


  Chocolate: ["ChocolateBars", "ChocolateCandies", "ChocolateChips", "ChocolateCream"],
  CookiesAndBiscuits: ["Biscuits", "Cookies", "Wafers"],
  GumsAndMints: ["CandiesAndLollipops", "Gums", "JellyAndGummies", "Marshmallow", "Mints"],


  Butter: ["ButterBlocks", "ButterRolls", "PlantBasedButter", "SprayButter", "TruffleButter"],
  Cheese: ["BlueCheese", "Cheddar", "Cottage", "CreamCheese", "Emmental", "Feta", "GoudaAndEdam", "HalloumiAndAkkawi", "Kashkaval", "Mozzarella", "SlicedCheese", "SpecialtyCheese"],
  Cream: ["CookingCream", "ThickCream", "WhippingCream"],
  Eggs: ["FreshEggs", "LiquidEggs", "QuailAndDuckEggs"],
  Milk: ["CondenseAndEvaporatedMilk", "FreshMilk", "LongLifeMilk", "MilkPowder", "PlantBasedMilk"],
  YogurtAndLabneh: ["CustardAndPudding", "Laban", "Labneh", "Yoghurt"],


  FrozenFishAndSeafood: ["FrozenFish", "FrozenSeafood"],
  FrozenFruitsAndVegetables: ["FrozenFruits", "FrozenVegetables"],
  FrozenMealsAndAppentizers: ["FrozenAppetizers", "FrozenFrenchFries", "FrozenMeatAppetizers", "FrozenPizzaAndPastries", "FrozenSeafoodMeals", "FrozenVegetablesAppetiers"],
  FrozenMeatAndPoultry: ["FrozenBeef", "FrozenChicken", "FrozenDuckAndQuail", "FrozenLamb"],
  FrozenSweetsAndDesserts: ["FrozenDesserts", "FrozenYoghurts", "IceCream"],

  FreshFruits: ["ApplesAndPears", "ApricotsAndPlums", "Berries", "Cherries", "CitrusFruits", "Melons", "PeachesAndNectarines", "TropicalFruits"],
  FreshVegetables: ["BeansAndPeas", "EdiblePlantStem", "Flowers", "HerbsAndleaves", "Marrow", "Mushrooms", "OnionsAndGarlic", "Roots", "SaladVegetables", "Vegetales Others"],

  FishAndSeafood: ["Fish", "Seafood"],
  Meat: ["Beef", "Camel", 'Goat', "Lamb"],
  Poultry: ["Chicken", "Duck", "Quail", "Turkey"],

  BakingDecorations: ["BakingCoatings", "BakingFillings", "BakingToppings"],
  BakingIngredients: ["BakingMix", "BakingPowderAndSoda", "BreadCrumbs", "CakeMix", "Flour", "FoodAdditives", "FoodColors", "Gelatin", "Powders", "Semolina", "Vanilla", "WhippingCreamPowder", "Yeast"],
  CannedFood: ["CannedFish", "CannedMeat", "CannedSeafood", "CannedVegetables"],
  Cereals: ["BreakfastCereals", "FitnessCereals", "Granola", "Oats"],
  DipsAndCondiments: ["ChutneyAndRelish", "Dips", "Ketchup", "Mayonnaise", "Mustared", "Paste", "SaladDressings", "Sauce", "Vinegar"],
  DryGroceryIndustrialIngredients: ["DryGrocery", "IndustrialIngredients"],
  GrainsAndPulses: ['Barley', "Bulgur", "Corn", "DryLegumes", "Millet", "PastaAndNoodles", "Quinoa", "Rice", "Wheat"],
  HoneyAndSyrups: ["Honey", "Syrup"],
  InstantFood: ["InstantNoodles", "InstantRice", "InstantSauceAndPasta", "InstantSoup", "MashedPotatoes", "ReadyToEat"],
  JamsAndSpreads: ["JamsAndMarmalades", "Spreads"],
  OilsAndFats: ["CoconutOil", "FruitOils", "Ghee", "Margarine", "MixedOils", "OliveOil", "SeedAndNutOils", "VefetableOils"],
  OlivesAndPickles: ["BlackAndOlives", "FruitPicklesAndPreserves", "GreenAndOlives", "MixedAndOlives", "MixedPicklesAndPreserves", "VegetablesAndPickles"],
  Snacks: ["Chips", "Crackers", "NutAndSeedSnacks", "PopcornAndPuffs"],
  SpicesAndSeasonings: ['DryFruitsAndVegetables', "DryHerbs", "DrySeedsAndNuts", "Salt", "Spices"],
  Stock: ['BeefStock', "ChickenStock", "SeaFoodStock", "VegetableStock"],
  SugarAndSugarAlternatives: ['ArtificialSweeteners', "BrownSugar", "SugarAlternatives", "WhiteSugar"],



  BabyBath: ["BabyBathAccessories", "BabyBathSeatsAndStands", "BabyBathTowelsAndRobes", "BabyBathtubs", "BabyBodyWash", "BabyConditioner", "BabyNonSlipBathmats", "BabyShampoo", "BabySpongesAndWashCloths", "BabyWashBowls"],
  BabyHealthCareAndGrooming: ["BabyCombsAndBrushes", "BabyCottonPadsAndBuds", "BabyNailCare", "BabyNasalAspirators", "BabyNebulizers", "BabyOralCare", "BabyScales", "BabyThermometers", "BabyWetWipes"],
  BabySafety: ["BabyCrawlingPads", "BabyLeashesAndHarnesses", "BabyMonitorsAndCameras", "BabySafetyGates", "BedRails"],
  BabySkinCare: ["BabyCreamAndLotion", "BabyOil", "BabyPerfume", "BabyPowder", "BabySunscreen"],

  BabyClothing: ["BabyCapsBeaniesAndScarfs", "BabyClothingSets", "BabyCoatsAndJackets", "BabyCostumes", "BabyDresses", "BabyDungarees", "BabyHoodiesAndSweatshirts", "BabyJeans", "BabyLeggingsAndPants", "BabyMittens", "BabyRompersAndJumpsuits", "BabyShorts", "BabySkirts", "BabySleepsuitsAndPajamas", "BabySwimwear", "BabyTshirtsAndShirts", "BabyTights", "BabyVests", "BodysuitsAndInnerwear", "NewbornClothingSets"],
  BabyClothingAccessories: ["BabyBellyWarmers", "BabyHairAccessories", "BabySafetyPins"],
  BabyFootwear: ["BabyShoes", "BabySocksAndBooties"],

  BabyDiapers: ["DisposableBabyDiapers", "ReusableBabyDiapers"],
  ChangingPads: ["ChangingPadsAndMats", "WaterproofSheets"],
  DiaperingAccessories: ["DiaperPailsAndRefills", "DisposableDiaperBags"],
  PottyTraining: ["Potties", "ToddlerToiletSeats"],

  BabyFeeding: ["BabyCups", "BabyFeeders", "BabyFeedingSets", "BabyFoodStorage", "BabyPlaceMats", "BabyPlatesAndBowls", "BabySpoonsAndForks"],
  BabyFood: ["BabyCerealsAndMeals", "BabyFormula", "BabyJuice", "BabySnacks"],
  BibsAndBurpCloths: ["BabyBibs", "BabyBurpCloths"],
  BottleFeeding: ["BabyBottlesAndNipples", "BottleCleaningProducts", "BottleDryersAndSterilizers", "BottleWarmers", "MilkPowderDispensers", "WaterThermos"],
  Breastfeeding: ["BreastCreams", "BreastPumps", "BreastShieldsAndShells", "MilkStorageBags", "NursingCovers", "NursingPads", "NursingPillows"],
  PacifiersAndTeethers: ["BabyPacifiers", "BabyTeethers", "PacifierHolders"],

  Activity: ["BabyBouncersAndSwings", "BabyGymsAndPlaymats", "BabyPlaypens", "BabyWalkersAndJumpers"],
  ChairsAndSeats: ["HighchairsAndFeedingBoosters", "ToddlerChairsAndSofas"],
  StrollersAndCarSeats: ["CarSeatBases", "CarSeatPartsAndAccessories", "CarSeatsAndBoosters", "StrollerPartsAndAccessories", "StrollersAndPrams", "TravelSystems"],
  Travel: ["BabyCarriersAndWraps", "BabyCarryCots", "BabyDiaperBags", "BabyTravelCots"],

  BabyBeddings: ["BabyBlanketsAndSwaddles", "BabyComforterSets", "BabyPillowCases", "BabyPillows", "BedBumpers", "BedSheetsAndMattressProtectors", "SleepingBagsAndNests"],
  BabyFurniture: ["BabyDrawersAndShelves", "BabyMattresses", "BabyRoomCarpets", "BabyWardrobes", "ChangingTables", "CribsAndBeds"],

  MakeupToolsAndAccessories: ["BlottingPaper", "EyebrowRazors", "EyebrowTweezers", "EyelashCurlers", "FoundationPlates", "MakeupBags", "MakeupBrushes", "MakeupMirrors", "MakeupPencilSharpeners", "MekeupStencils", "MakeupToolKits"],
  NailCareTools: ["CallusRemover", "ElectricNailDrills", "ElectircNailDryers", "FootFiles", "NailCleaningBrushes", "NailClippers", "nailFilesAndBuffers", "ToeSeparator"],
  SkincareTools: ["FacialCleansingTool"],

  Perfumes: ["BodySpraysAndMists", "EauDeCologne", "EauDeParfum", "EauDeToilette", "FragranceGiftSets", "HairPerfumesAndMists", "Oud", "PerfumeOils"],

  BodyArt: ["TattooStencils", "TattooTools"],
  BodyMakeup: ["BodyBronzers", "BodyConcealers", "BodyGlitters"],
  EyeMakeup: ["EyePencil", "EyeShadow", "Eyeliner", "FalseLashesAndAdhesives", "LashEnhancersAndPrimers", "Mascara"],
  EyebrowMakeup: ["EyebrowGel", "EyebrowMascara", "EyebrowPencil", "EyebrowPowder"],
  FaceMakeup: ["BBAndCCCream", "Blush", "Bronzer", "ConcealerAndCorrector", "Contour", "Foundation", "Highlighter", "MakeupSets", "Powder", "Primer", "SettingSpray"],
  Lips: ["LipGloss", "LipLiner", "Lipstick"],

  NailArt: ["FalseNailsAdhesives", "NailArtTemplates", "NailArtTools", "NailDecoration", "NailStickers"],
  NailCareProducts: ["CuticleRemover", "NailPolish", "NailPolishRemover", "NailTreatments", "TopAndBaseCoat"],

  EyeCare: ["EyeCreamsAndGel", "EyeMakeupRemovers", "EyeMasks", "EyeSerums"],
  FaceCare: ["FaceCareSets", "FaceCreamsAndMoisturizers", "FaceGel", "FaceOils", "FaceScrubs", "FaceSerums", "FaceToners", "FacialMasks", "MakeupRemoversAndCleansers"],
  LipCare: ["LipBalms", "LipScrubs"],
  SunCareAndTanning: ["AfterSunCare", "Self-Tanners", "Sunscreen"],

  CleaningAppliances: ["ElectricDeepCleaners", "ElectricFloorCleaners",  "ElectricWindowCleaners", "SteamMops", "VacuumCleaners"],
  CoffeeAndEspressoMachines: ["CoffeeBeanGrinders", "CoffeeMachines", "EspressoMachines"],
  CollingAppliances: ["AirConditioners", "AirCoolers", "AirDehumidifiers", "AirHumidifiers", "AirPurifiers", "CoolingFans"],
  HeatingAppliances: ['ElectricFireplaces', "ElectricHeaters", "GasHeaters", "KeroseneHeaters", "OilHeaters"],
  LargeKitchenApliances: ["Dishwashers", "Freezers", "Microwaves", "Ovens", "RangeHoods", "Refrigerators", "StovesAndHobs", "WaterColersAndDispensers"],
  LaundaryAppliances: ["ClothesSteamers", "Dryers", "Irons", "SewingMachines", "WashingMachines"],
  SmallKitchenAppliances: ["AirAndDeepFryers", "Blenders", "ChocolateFountains", "ChoppersAndMinceres", "EggCookers", "ElectricKettles", "FoodDehydrators", "FoodMakers", "FoodProcessors", "GrillsAndToasters", "IceMakers", "Juicers", "MeatGrinders", "Mixers", "SealingMachines", "SmartPots"],

  BarFurniture: ["BarChairsAndStools", "BarTables"],
  HairSalonFurniture: ["HairdressingChairs", "NailCareChairs", "NailCareTables", "SalonMassageBeds", "SalonStationMirrors", "SalonTrolleys", "ShampooChairs"],
  HealthAndMedicalFurniture: ["HospitalBeds", "HospitalCabinets", "HospitalChairs", "HospitalDripStands", "HospitalTables", "HospitalTrolleys", "MedicalMassageBeds"],
  HotelFurniture: ["HotelBeds", "HotelChairs", "HotelSofas", "HoteTables", "HotelTrolleys", "LuggageRacks"],
  RestaurantFurniture: ["RestaurantChairs", "RestaurantDiningTables", "RestaurantSofas", "RestaurantTables", "RestaurantTrolleys", "RestaurantWardrobes"],
  SchoolFurniture: ["KindergartenTables", "SchoolChairs", "SchoolTables", "SchoolTrolleys", "SchoolWardrobes"],

  BBQAndGrills: ["BBQAccessories", "BBQCleaningTools", "BbqFans", "BbqGrillsAndSmokers", "BbqMittens", "BbqToolsAndSets", "BarbecueKettles", "Charcoal", "CharcoalStarters", "FireWood", "GrillBrushes", "GrillCovers"],
  GardenDecor: ["ArchesAndArbors", "CobblesAndPebbles", "DecorativeStonesAndStatues", "FencesNettingsAndGates", "Fountains", "PergolasAndTrellises", "ShedsAndStorage"],
  GardeningTools: ["AgriculturalSeeds", "FertilizersAndComposts", "FlowerPotsAndPlanters", "GardenCarts", "GardeningGloves", "GrassShears", "PlantsAndFlowers", "ShovelsAndRakes"],
  OutdoorFurniture: ['GardenSwings', "Hammocks", "OutdoorSeats", 'outdoorShades', "OutdoorTables", "SunLoungers"],
  PestControl: ["Electric", "FoggersAndSprays", "Gel", "Manual"],
  WateringAndIrrigation: ["HoseConnectors", "HosesAndReels", "IrrigationsSystems", "Sprayers", "SuctionFilters", "WaterPumps", "WateringPails"],

  ArtworkAndFrames: ["ArtCards", "Mosaics", "PhotoFrames", "WallArtAndFrames", "WallHangings", "WallStickers", "Wallpaper"],
  Clocks: ["FloorClocks", "SpecialtyClocks", "TableClocks", "WallClocks"],
  DecorativeAccessories: ["ArtificialPlantsAndFlowers", "DoorHangingAccessories", "DriedPlantsAndPhoto", "OrnamentsAndScuptures", "Plaques", "RoomDividers", "SeasonalDecoration",  "TissueBoxCovers", "TrophiesAndMedals", "VasesAndBowls"],
  HomeFragrances: ["AromaOilsAndDiffusers", "BakhoorAndIncense", "CandleHolders", "Candles", "IncenseBurnersAndHolders"],
  Islamic: ["DigitalTallyCounter", "QiblahCompasses", "Quran", "QuranBoxes", "QuranCovers", "QuranHolders", "QuranReaderPens"],
  Mirrors: ["FloorMirrors", "WalLMirrors"],
  PartySupplies: ["Balloons", "BalloonsPump", "BirthdayCandles", "BodyAndFacePaint", "CakeToper", "GlowSticks", "GreetingCards", "GuestBook", "InvitationCards", "Masks", "PartyBadges", "PartyBanners", "PartyBlowouts", "PartyBubbles", "Partygames", "PartyHairBands", "PartyHats", "PartyHorns", "PartyLights", "PartyPopper"],




  Bedrooms: ["BedBases", "BedroomSets", "Beds", "BedsideTables", "DrawerUnits", "Dressers", "Headboards", "Mattresses", "SpringBoxes", "Wardrobes"],
  DiningRooms: ["DiningChairs", "DiningTableSets", "DiningTables", "SideboardsAndBuffets",],
  KidsAndBabyFurniture: ["BabyAndToddlerMattresses", "BabyBedsAndCribs", "JuniorChair", 'ToddlerBeds'],
  KitchenFurniture: ["IslandsAndWorktops", "KitchenChairsAndStools"],
  LivingRooms: ["ChairsAndBenches", "CoffeeTables", "ConsoleTables", "PoufsAndBeanbags", "Recliners", "SideTables", "SofaBedsAndDayBeds", "SofasAndSofaSets", "TvTables"],


  Bedding: ["BedSheets", "BedSkirts", "BedTents", "BeddingAccessories", "BeddingSets", "BlanketsAndThrows", "DuvetCovers", "Duvets", "MattressProtectors", "PillowsAndCushionCover", "SeatRestsAndChair", "Slipcovers"],
  CarpetsAndRugs: ["Carpets", "Doormats", "Mats", "PrayerMats", "Rugs", "Tapestry"],
  CurtainsAndBlinds: ["Blinds", "Shades", "CurtainPolesAndRods", "CurtainTracks", "Curtains"],

  BathroomAccessories: ["BathMats", "BathTowels", "Bathrobes", "BathroomMats", "BathtubPillows", "BeachTowels", "HairTowels", "HandTowels", "ShowerCurtains", "ShapTraysAndDispenser", "ToothbrushHolders", "ToothpasteSqueezers"],
  CleaningSupplies: ["AirFresheners", "BathroomCleaners", "DishCleaners", "DrainCleaners", "FloorCleaners", "FurnitureCleaners", "GlassCleaners", "KitchenCleaners", "LaundryCleaners", "MultiPurposeCleaners"],
  CleaningTools: ["BroomsAndDustpans", "CleaningBrushes", "CleaningCaddies", "CleaningCloths", "CleaningGloves", "CleaningWipers", "Dusters", "LintRemovers", "MoppingTools", "ScouringPads", "Sponges", "SteelScrubbers", "ToiletBrushes", "TrashBins"],
  DisposableHygieneProducts: ["FacialTissuePaper", "KitchenPaper", "Napkins", "ToiletPaper", "ToiletSeatCover", "WetWipes"],
  DisposableTableware: ["DsiposableBowls", "DisposableCups", "DisposableCutlery", 'DisposableDinnerwa', "DisposablePlates", "DisposableStraws"],
  HomeStorageAndOrganization: ["HooksAndWallOrganization", "StorageBags", "StorageBoxes", "StorageUnits"],
  KitchenEssentials: ["AluminumFoil", "BankingPaper", "ClingFilm", "FoodStorageBags", "SofraSheets", "TrashBags"],
  KitchenLines: ["Aprons", "KitchenTowels"],
  KitchenStorageAndOrganisation: ["DishRacks", "KitchenStage", "StorageContainers", "StorageJarsAndCanisters"],
  LaundryStorageOrganization: ["ClothesHangers", "ClothesStands", "Clothesslines", "Clothespins", "DryingRacksAndHangers", "IronHolders", "IroningBoardsCovers", "IroningBoards", "LaundryBaskets"],
  PhotoAlbums: ["PhotoAlbums"],
  SewingAndAccessories: ["Buckles", "CrochetHooks", "Fabrics", "KnittingNeedles", "PatternsAndTemplate", "Threads", "Zippers"],
  StorageAndOrganization: ["Cabinets", "DecorativeBasket", "PaperTowelDispensers", "Storage", "Wardrobe"],
  TableEssentials: ["Ashtrays", "NapkingRingsAndHolder", "PadsAndMats", "TableNapkins", "TableRunnersAndCover", "ToothpicksHolders", "Toothpicks"],


  Bakeware: ["BakewareSets", "BakingAndPastryTools", "BakingMats", "BakingPans", "CakeTools", "CookieTools", "OvenMittens", "PizzaTools", "RollingPins"],
  CoffeeAndTeaTools: ["CoffeeFilters", "CoffeePots", "MilkFrothers", "MilkFrothingPitchers", "Teapots"],
  Cookware: ['CookingPots', "CookwareSets", "FryingPans", "GrillPans", "PressureCookers", "RoastingPans", "SaucePans", "Works"],
  Dinnerware: ['Appetizer', "Bowls", "DinnerDishesAndPlates", "DinnerwareSets", "SauceBoats", "ServingBaskets", "ServingStands", "ServingTrays", "SugarBowls"],
  Drinkware: ["ArabianCoffeeCups", "BeerGlasses", "CocktailShakers", "Cups", "DrinkwareSets", "Flasks", "Glasses", "Mugs", "Pitchers", "ThermosFlasks", "WaterBottles"],
  KitchenKnivesAndAccessories: ['ChoppingBoards', "KitchenKnives", "KitchenScissors", "KnifeHolders", "KnifeSets", "KnifeSharpeners",],
  KitchenToolsAndUtensils: ["AppleCorersAndSlicers", "BottleOpeners", "CanOpeners", "CookingTools", "EffPoachers", "EggSeparators", "FoodMills", "Funnels", "GarlicPresses", "GratersAndPeelers", "IceBoxes", "IceBucketsAndTongs", "KitchenMeasuringTools", "LidsAndCovers", "MeatTenderizers", "MelonBallers", "MillsAndShakers", "MortorAndPestles", "Nutcrackers", "PastaTools", "PotatoMashers", "PotatoRicers", "RefrigeratorMagnet", "SaladTools", "SeafoodTools", "Slicers", "SpecialtyTools", "StrainersAndColanders", "Tongs"],
  Tableware: ['Chopsticks', "CutlerySets", "DinnerKnives", "Forks", "Spoons", "Spreaders", "Stirrers"],

  Printers3D: ["Printers3D"],

  AgriculturalMachineryParts: ["AgriculturalMachineryParts"],
  AgriculturalSprayer: ["AgriculturalSprayer"],
  AnimalAndPoultryHusbandrEquipment: ["AnimalAndPoultryHusbandryEquipment"],
  AquacultureMachineAerators: ['AquacultureMachineAerators'],
  Balers: ["Balers"],
  BiomassBriquetteMachines: ["BiomassBriquetteMachines"],
  BiomassDryers: ["BiomassDryers"],
  CompostMakingMachines: ["CompostMakingMachines"],
  Cultivators: ["Cultivators"],
  EggIncubators: ["EggIncubators"],
  FarmIrrigationSystem: ["FarmIrrigationSystem"],
  FarmTrailer: ["FarmTrailer"],
  FeedProcessingMachines: ["FeedProcessingMachines"],
  FertilizerSpreaders: ["FertilizerSpreaders"],
  ForestryMachinery: ["ForestryMachinery"],
  Harvesters: ["Harvesters"],
  IndoorFarmingAndHydroponicsMachines: ["LedGrowLightAndSensors"],
  IrrigationEquipment: ["IrrigationEquipment"],
  MilkingMachines: ["MilkingMachines"],
  OilPressers: ["OilPressers"],
  OtherAgriculturalMachineryAndEquipments: ["OtherAgriculturalMachineryAndEquipments"],
  OtherFarmMachines: ["OtherFarmMachines"],
  SeedProcessingMachines: ["SeedProcessingMachines"],
  //problem 2
  Seeders: ["Seeders"],
  Shellers: ["Shellers"],
  Silos: ["Silos"],
  SlaughteringEquipment: ["SlaughteringEquipment"],
  TowableBachoe: ["TowableBachoe"],
  Tractors: ["Tractors"],



  ApparelAndTextileMachineryParts: ["ApparelMachineParts", "CapMakingMachineParts", "GloveMakingMachine", "HometextileProduct", "LeatherProductionMachineParts", "ShoemakingMachineParts", "SockKnittingMachine", "TextileMachineParts"],
  ApparelMachinery: ["ButtonMakingMachines", "ButtonholeMachines", "EmbroideryMachines", "IndustrialGarmentPressMachine", "IndustrialGarmentSteamers", "LaceMachines", "OtherApparelMachine", "Overlockers", "RhinestoneMachines", "SewingMachines", "ZipperMakingMachines"],
  CapMakingMachines: ["CapMakingMachineParts"],
  HomeTextileProduct: ["FeltingMachines", "OtherHomeTextileProduct", "QuiltingMachines", "TowelMakingMachines"],
  IroningAndWashingEquipments: ["DryingEquipments", "IroningAndWashingEquipments", "IroningMachines", "WashingMachines"],
  LeatherProductionMachinery: ["LeatherProductionMachineParts"],
  ShoeMakingMachines: ["HeelSeatMachines", "HeelNailingMachines", "LaminationMachines", "OtherShoemakingMachines", "ShoeCementingMachines", "ShoeEyeletingMachines", "ShoeMouldingMachines", "SockKnittingMachines", "SolePressMachines", "ToeLastingMachines"],
  TextileMachinery: ["BleachingMachines", "BraidingMachines", "CardingMachines", "ClothCuttingMachines", "KnittingMachines", "MaskMakingMachines", "NetMachines", "NonwovenMachines", "OtherTexttileMachines", "SpinningMachines", "TextileDyeingMachines", "TextileFinishingMachines"],

  ChemicalMachineryAndEquipment: ["3DBlu-rayPlayer", "ChemicalMachineParts", "ChemicalStorageEquipment", "ChemicalTransportation", "DryingEquipment", "Granulators", "GrindingEquipment", "HeatTransferEquipment", "MixingEquipment", "OtherChemicalMachines", "PressureVesseles", "Reactors", "SeparationEquipment"],
  CosmeticsProductionEquipment: ["CosmeticsProductionEquipment"],
  Crystalizer: ["Crystalizer"],
  PharmaceuticalMachinery: ["CapsuleFillingMachines", "CapsulePolisher", "Extractor", "FilmCoatingMachine", "PharamaceuticalFilligMachine", "PharmaceuticalMachinesParts", "PharmaceuticalMachinery", "SoftGelatinEncapsulationMachines", "TabletCounter", "TabletPress"],


  AirCleaningEquipment: ["AirCleaningEquipmentParts", "AirShower", "Dehumidifier", "Humidifier", "OtherAirCleaningEquipment"],
  CleaningEquipmentParts: ["CleaningEquipmentParts"],
  CornerCleaningMachines: ["CornerCleaningMachines"],
  DishwashingEquipments: ["DishwashingEquipments"],
  FiltrationEquipment: ["AirFilter", "DustCollector", "FilterPressEquipment", "FloorSweeper", "HighPressureCleaer", "IndustrialUltrasonicCleaner", "MachineOilFilter", "WashingEquipment", "WaterFilter"],

  AbrasiveMachines: ["AbrasiveMachines"],
  BuildingMaterialMachinery: ["BoardMakingMachinery", "BrickMakingMachinery", "BuildingMaterialMaking", "CementMakingMachine", "DryMortarMachines", "DuctMakingMachines", "Floorboards", "GlassProductionMachines", "GypsumPowderMachines", "PipeMakingMachines", "PlasterOfParisMachines", "SandMakingMachinery", "StoneMachinery"],
  ConcreteMachinery: ["ConcreteBatchingPlant", "ConcreateMixerTruk", "ConcreteMixers", "ConcretePumps", "ConcreteVibrator", "ShotcreteMachines"],
  ConstructionLifter: ["ConstructionLifter"],
  ConstructionMachinery: ["Bucket", "EarthAugers", "ExcavatorRakes", "Grapples", "HydraulicBreakers", "HydraulicShears", "QuickHitch", "Rippers"],
  Cranes: ["BridgeCranes", "FloatingCranes", "GantryCranes", "JibCranes", "OherCranes", "PortalCranes", "TowerCranes", "TruckCranes"],
  CuttingMachines: ["CuttingMachines"],
  DrillingMachines: ["DrillingMachines"],
  EarthMovingMachines: ["Bulldozers", "Compactors", "Excavators", "Loaders"],
  ElectronicsProductionsMachinery: ["ElectronicsProductionsMachinery"],
  GaugesIndicatorsAndMeter: ["Gauges", "Indicators", "Meters"],
  MortarSprayMachines: ["MortarSprayMachines"],
  MunicipalMachinery: ["GarbageTruck", "HydroseedingMachine", "RoadSweeper",  "SnowSweeper", "WateringCart"],
  OtherConstructionMachinery: ["OtherConstructionMachinery"],
  PileDriver: ["PileDriver"],
  PipeJackingMachines: ["PipeJackingMachines"],
  PolishingMachines: ["PolishingMachines"],
  Rammers: ["Rammers"],
  RenderingMachines: ["RenderingMachines"],
  RoadMachinery: ["AsphaltMixers", "ConcreteCutter", "ConcreteGrinder", "ConcreteSacrifier", "MotorGraders", "Pavers", "PowerTowel", "RoaMarkingMachines", "RoadGroovingMachines", "RoadRoller", "RoadSealingMachines"],
  //problem 3
  ScientificLabEquipment: ["ScientificLabEquipment"],


  BakingEquipment: ["BakingOven", "BreadMakingMachine", "CakeMachine", "DoughMixer", "DoughSheeter", "OtherBakingEquipment"],
  BeanProductProcessingMachinery: ["BeanProductProcessingMachinery"],
  BeverageProcessingMachines: ["BeverageMachineParts", "Concentrator", "DispensingMachines", "Emulsifier", "FermentingEquipment", "Filter", "HeatExchanger", "Homogenizer", "JuiceExtractor", "Mixer", "OtherBeverageMachines", "Separator", "Sterilizer", "StorageTank", "Wahser"],
  CoffeeMachine: ["CoffeeBeanRoasters", "CoffeeMakingEquipment", "OtherCoffeeMachines"],
  DairyProcessingMachine: ["DairyProcessingMachine"],
  EggProcessingMachines: ["EggProcessingMachines"],
  FoodProcessingMachines: [" FoodProcessingMachines"],
  FoodSterlizer: ["FoodSterlizer"],
  FruitAndVegetableProcessingMachines: ["FruitAndVegetableGradingMachines", "FruitAndVegetableJuiceMachines", "FruitAndVegetablePeelingMachines", "VegetableCutter"],

  Fryer: ["Fryer"],
  GrainProcessingMachines: ["FlourMill", "PeelingMill", "RiceMill"],
  GrainProductMakingMachines: ["GrainProductMakingMachines"],
  HoneyProcessingMachines: ["HoneyProcessingMachines"],
  KitchenMachines: ["KitchenMachines"],
  MeatProcessingMachine: ["MeatBowlCutter", "MeatMincer", "MeatSlicer", "SausageStuffer"],
  MeatProductionMakingMachines: ["MeatProductionMakingMachines"],
  NutsProcessingMachines: ["CashewProcessingMachines", "CocoaProcessingMachines"],
  OtherFoodProcessing: ["OtherFoodProcessing"],
  Pasteurizer: ["Pasteurizer"],
  PetFoodProcessingMachines: ["PetFoodProcessingMachines"],
  SeasoningProcessing: ["PeanutButterMakingMachines", "SpiceAndSauceMachines", "SugarAndSaltProcessingMachines"],
  SnackMacine: ["BiscuitMakingMachines", "ChocolateMakingMachines", "ChurrosMachine", "CottonCandyMachines", "DonutMachine", "FoodTruck", "IceCreamMachines", "PopcornMachine", "PopsicleMachine", "PotatoChipsMakingMachines"],



  AuxiliaryPackagingMachines: ["AuxiliaryPackagingMachines"],
  BlisterPackahingMachines: ["BlisterPackahingMachines"],
  BoxingMachine: ["BoxingMachine"],
  CappingMachines: ["CappingMachines"],
  CoatingMachines: ["CoatingMachines"],
  EmbossingMachines: ["EmbossingMachines"],
  FillingMachines: ["FillingMachines"],
  GluingMachines: ["GluingMachines"],
  LabelingMachines: ["LabelingMachines"],
  LaminatingMachines: ["LaminatingMachines"],
  MultiFunctionPackagingMachines: ["MultiFunctionPackagingMachines"],
  OtherPackaginMachines: ["OtherPackaginMachines"],
  PackagingFormingMachines: ["PackagingFormingMachines"],
  PackagingLine: ["PackagingLine"],
  PackagingMachinery: ["PackagingMachinery"],
  PackagingMateialMachines: ["BagMakingMachinesParts", "BagMakingMachines", "BeltmakingMachineParts", "BeltMakingMachines"],
  SealingMachines: ["SealingMachines"],
  VacuumPackagingMachines: ["VacuumPackagingMachines"],
  WrappingMachines: ["WrappingMachines"],

  FoamCuttingMachine: ["FoamCuttingMachine"],
  FoamMachinery: ["FoamMachinery"],
  InjectionMoldingMachines: ["InjectionMoldingMachines"],
  LatheMachines: ["LatheMachines"],
  OtherPlasticProductMakingMachinery: ["OtherPlasticProductMakingMachinery"],
  OtherPlasticAndRubberMachinery: ["OtherPlasticAndRubberMachinery"],
  PipeBellingMachines: ["PipeBellingMachines"],
  PlasticAndRubberMachinery: ["PlasticAndRubberMachinery"],
  PlasticAuxiliaryEquipment: ["MouldTempreratureController", "PlasticWindingMachines"],
  PlasticBowlingMachinery: ["BlownFilmProducionMachines", "ExtrusionBlowMoldingMachines", "InjectionBlowMouldingMachines", "StretchBlowMouldingMachines"],
  PlasticCuttingMachinery: ["PlasticCuttingMachinery"],
  PlasticExtruders: ["PlasticExtruders"],
  PlasticFlockingMachinery: ["PlasticFlockingMachinery"],
  PlasticLaminatingMachinery: ["PlasticLaminatingMachinery"],
  PlasticRawMaterialMachinery: ["PlasticDryingMachines", "PlasticGranulators", "PlasticLoader", "PlasticMixer"],
  PlasticRecyclingMachinery: ["PlasticCrushingMachinery", "RecycleWashingLine"],
  PlasticRotationalMoldingMachines: ["PlasticRotationalMoldingMachines"],
  PlasticThermoformingMachines: ["PlasticThermoformingMachines"],
  RubberProcessingMachines: ["InternalMixers", "OtherRubberProcess", "RubberBaleCutters", "RubberCalenders", "RubberExtruders", "RubberKneadears", "RubberTwoRollMills"],
  RubberProductMakingMachines: ["RubberProductMakingMachines"],
  RubberRecyclingMachines: ["RubberPryolysisMachines", "TireRetreadMachines", "TireShredders"],


  ArtAndCraftPaper: ["ArtAndCraftPaper"],
  ArtAndCraftSets: ["ArtAndCraftSets"],
  BeadsSequinsAndGlitter: ["BeadsSequinsAndGlitter"],
  CanvasAndArtPads: ["CanvasAndArtPads"],
  CraftAccessories: ["CraftAccessories"],
  CuttingTools: ["CuttingTools"],
  GlueGunsAndSticks: ["GlueGunsAndSticks"],
  MeasuringTools: ["MeasuringTools"],
  PaintAndColors: ["PaintAndColors"],
  PaintBrushes: ["PaintBrushes"],
  Palettes: ["Palettes"],
  SewingTools: ["SewingTools"],
  YarnAndThreads: ["YarnAndThreads"],

  BoardAccessories: ["BoardAccessories"],
  BulletinBoards: ["BulletinBoards"],
  ChalkBoards: ["ChalkBoards"],
  EaselsAndEaselPads: ["EaselsAndEaselPads"],
  GlassBoards: ["GlassBoards"],
  WhiteBoards: ["WhiteBoards"],

  BookReaders: ["BookReaders"],
  ChildrensBooks: ["ActivityBooksAndGames", "AnimalsAndPets", "CraftsAndHobbies", "EarlyLearning", "FictionAndStories", "ScienceAndNature", "StudyingAndWorkbooks"],
  Fiction: ["ComicAndGraphicNovels", "CrimeAndMystery", "HorrorAndThriller", "LiteratureAndPoetry", "NewAge", "Romance", "ScienceFiction", "YoungAdults"],
  NonFiction: ["ArtAndDesign", "BiographyAndMemories", "BusinessAndEconomics", "ComputersAndTechnology", "CookBooks", "EducationAndReference", "EngineeringAndScience", "HealthAndNutrition", "HistoryAndPolitics", "HomeAndGarden", "Humour", "ParentingAndRelationships", "Psychology", "ReligiousBooks", "SocialScience", 'SportsAndLeisure', "TravelAndTourism"],

  BinsAndBaskets: ["BinsAndBaskets"],
  BusinessCardsAndOrganizers: ["BusinessCardsAndOrganizers"],
  DeskOrganizersAndAccessories: ["DeskOrganizersAndAccessories"],
  DocumentTraysAndDrawing: ["DocumentTraysAndDrawing"],
  PenMemoAndClipHolders: ["PenMemoAndClipHolders"],
  DividersAndBookmarks: ["DividersAndBookmarks"],
  DocumentBagsAndDisplayBooks: ["DocumentBagsAndDisplayBooks"],
  FileStorage: ["FileStorage"],
  HangingAndExpandingFiles: ["HangingAndExpandingFiles"],
  LaminatingFilms: ["LaminatingFilms"],
  LeverArchAndBoxFiles: ["LeverArchAndBoxFiles"],
  RingBindersAndViewBinder: ["RingBindersAndViewBinder"],
  SuspensionAndReportFiles: ["SuspensionAndReportFiles"],

  Batteries: ["Batteries"],
  BinderClipsAndPins: ["BinderClipsAndPins"],
  Clipboards: ["Clipboards"],
  Envelopes: ["Envelopes"],
  GeneralAccessories: ["GeneralAccessories"],
  KeyBoxAndAccessories: ["KeyBoxAndAccessories"],
  NameBadgesAndLanyari: ["NameBadgesAndLanyari"],
  Punchers: ["Punchers"],
  RubberBands: ["RubberBands"],
  Rulers: ["Rulers"],
  Scissors: ["Scissors"],
  SignsLabelsAndStickers: ["SignsLabelsAndStickers"],
  StaplesAndStaplers: ["StaplesAndStaplers"],

  CabinetsAndDrawerUnits: ["Bookcases", "Cabinets", "DrawerUnits", "Shelves"],
  ChairsAndSeating: ["ChairMatsAndAccessories", "DeskChairs", "FootStoolAndFootrest", "OfficeSofasAndBenches", "SeatingAccessories", "VisitorChairs",],
  OfficeDesksAndTables: ["ConferenceAnMeeting", "DesksAndWorkstations", "DraftingTables", "PcGamingTables", "ReceptionDesks"],

  AttendanceMachines: ["AttendanceMachines"],
  BindingMachines: ["BindingMachines"],
  Calculators: ["Calculators"],
  CashHandlingMachines: ["CashHandlingMachines"],
  Laminators: ["Laminators"],
  PaperTrimmersCutt: ["PaperTrimmers&Cutt"],
  Safes: ["Safes"],
  Shredders: ["Shredders"],

  GiftBagsBoxesAndWraps: ["GiftBagsBoxesAndWraps"],
  PackagingPaperAndWraps: ["PackagingPaperAndWraps"],
  PackagingPouchAndBox: ["PackagingPouchAndBox"],

  AddressLabels: ["AddressLabels"],
  BarcodeLabels: ["BarcodeLabels"],
  DotMatrixPrinters: ["DotMatrixPrinters"],
  IdCardPrinters: ["IdCardPrinters"],
  InkJetPrinters: ["InkJetPrinters"],
  LabelMakers: ["LabelMakers"],
  LaserJetPrinter: ["LaserJetPrinter"],
  PrintersAndScannersAccessories: ["PrintersAndScannersAccessories"],
  Scanners: ["Scanners"],
  ShippingLabels: ["ShippingLabels"],

  ColorPaper: ["ColorPaper"],
  CopyPaper: ["CopyPaper"],
  PaperRolls: ["PaperRolls"],
  SpecialtyPaper: ["SpecialtyPaper"],

  DuctTapes: ["DuctTapes"],
  GluesAndAdhesives: ["GluesAndAdhesives"],
  MaskingTapes: ["MaskingTapes"],
  PackingTapes: ["PackingTapes"],
  SpecialtyTapes: ["SpecialtyTapes"],
  TapeDispensers: ["TapeDispensers"],
  TransparentTapes: ["TransparentTapes"],

  InkCartridges: ["InkCartridges"],
  TonersCartridges: ["TonersCartridges"],

  CorrectionPensAndFluids: ["CorrectionPensAndFluids"],
  GeometryAndScienceSupplies: ["GeometryAndScienceSupplies"],
  MarkersAndHighlighter: ["MarkersAndHighlighter"],
  PencilsAndLead: ["PencilsAndLead"],
  Pens: ["Pens"],
  SharpencersAndErasers: ["SharpencersAndErasers"],
  WritingAccessories: ["WritingAccessories"],

  AddressAndAccountingBooks: ["AddressAndAccountingBooks"],
  CalendarJournalAndDiaries: ["CalendarJournalAndDiaries"],
  NotebooksAndWritingPads: ["NotebooksAndWritingPads"],
  StickyNotesAndNoteCards: ["StickyNotesAndNoteCards"],

  HairAccessories: ["HairClips", "HairPins", "HairTies", "HeadBands", "Tiaras", "WigsAndHairExtensions"],
  HairCare: ["BeardCare", "Conditioner", "HairCareSets", "HairLossProducts", "HairMasks", "HairOilsAndSerums", "HairTreatments", "KeratinTreatments", "Shampoo"],
  HairColoring: ["HairPowder", "HairColoringToner", "HairColoringTreatments", "HairColoringTools", "HairColoringWax"],
  HairStylingProducts: ["HairCreams", "HairGels", "HairMousse", "HairSprays", "PomadesAndWaxes"],

  BathAndBody: ["BathAccessories", "BodyCreamsLotionsAndMoisturizers", "BodySoapAndWash", "BrushesSpongesAndGloves", "Condoms", "CottonBallsPadsAndSwabs", "DeodorantsAndAntiper", "EarPlugs", "FeminineCare", "FootPowder", "FootSpa", "HandSoapAndWash", "IncontinenceProduction", "Sanitizers", "ShowerCaps", "TalcumPowder"],
  HairSalonDisposables: ["DisposableAccessories", "DisposableBedRolls", "DisposableSlippers", "DisposableTowels", "DisposableUndergraments", "SterilizationPouches"],
  MassageAndRelaxation: ["BodyAndMassageOils", "MassageToolsAndAccessories"],
  OralAndDentalCate: ["DentalCareKits", "DentalFloss", "ElectricToothbrushes", "ManualToothbrushes", "MouthwashAndFresheness", "TeethWhitening", "tongueCleaners", "Toothpaste"],
  SavingsAndHairRemoval: ['Aftershaves', "ShavingCreams", "SugaringPaste", "WaxBeans", "WaxRollers", "WaxStrips"],

  HairStylingTools: ["CurlingIrons", "ElectricHairBrushes", "HairBraiders", "HairBrushes", "HairCombs", "HairDryers", "HairRollers", "HairScissors", "HairStemersAndHoods", "HairStraighteners", "HairdressingGowns", "MultiStylers"],
  ShavingAndHairRemovalTools: ["ElectricHairRemovalDevices", "ElectricShaversAndTrimmers", "LaserHairRemovalDevices", "ManualHairRemovalDevices", "RazorsAndBlades", "ShavingBrushes", "TemporaryCategory", "WaxApplicators", "WaxHeaters"],

  AnimalFeedsAndSupplements: ["AnimalFeedsAndSupplements"],
  PetApparelAndSupplements: ["CleaningSupplies", "CollarsAndleashes", "FeedingAndWateringSuipplies", "GroomingSupplies", "HealthSupplies", "PetApparelAndAccessories", "PetHeatLamps", "Toys", "TrainingAndBehaviour"],
  PetFood: [" Chews", "DryFoods", "Milk", "Treats", "WetFoods"],
  PetFurniture: [" Aquariums", "Beds", "Crates", "Gages"],

  CleaningSupplies: ["CleaningSupplies"],
  CollarsAndLeashes: ["CollarsAndLeashes"],
  FeedingAndWateringSupplies: ["Boottles", "Bowls", "FeedingMats", "FeedingSyringes", "FountainsAndFilters"],
  GroomingSupplies: ["GroomingSupplies"],
  HealthSupplies: ["HealthSupplies"],
  PetApparelAndAccessories: ["PetClothes", "PetShoesAndSocks"],
  PetHeatLamps: ["PetHeatLamps"],
  Toys: ["Toys"],
  TrainingAndBehaviorSupplies: ["TrainingAndBehaviorSupplies"],

  Chews: ["Chews"],
  DryFoods: ["DryFoods"],
  Milk: ["Milk"],
  Treats: ["Treats"],
  WetFoods: ["WetFoods"],

  Aquariums: ["Aquariums"],
  Beds: ["Beds"],
  Crates: ["Crates"],
  Gages: ["Gages"],

  ExerciseMachines: ["EllipticalTrainers", "ExerciseBikes", "MultiFunctionStations", "PilatesReformersAndParts", "PinLoadSelectionMachines", "PlateLoadedMachines", "Rowers", "SpinningBike", "Treadmills", "VibrationPlatformMachines"],
  FitnessAccessories: ["BalanceBoard", "Blocks", "BoxingGloves", "Chalk", "ExerciseBalls", "FitnessMats", "HandGrips", "JumpRopes", "ProtectiveGear", "PushUpsAndDipStands", "SaunaSuitsAndWaistTrimmers", "SportHoops", "StepPlatforms", "SupportSleevesAndBraces", "WaterAndShakerBottles"],
  WeightAndResistanceTraining: ["BarsAndCollars", "BEnchesAndRacks", "ExerciseBands", "WeightLiftingAccessories", "WeightStorage", "Weights"],

  BallGames: ["AmericanFootball", "BaseballAndSoftball", "Basketball", "Cricket", "Football", "Golf", "Hockey", "Netball", "Rugby", "Volleyball"],
  BikePartsAndTools: ["BikeAirPumps", "BikeBasketsAndBags", "BikeBellsAndMirrors", "BikeGpsAndElectronics", "BikeLocks", "BikeLubeAndGrease", "BikeParts", "BikeSeatsAndCovers", "BikeTiresTubesAndWheels"],
  BikesAndElectrinBikes: ["BikesAndElectrinBikes"],
  BoxingRings: ["BoxingGloves"],
  CampingAccessories: ["CampingAccessories"],
  CampingPersonalCare: ["CampingPersonalCare"],
  CampingTablesChair: ["CampingChair", "CampingFurniture", "CampingTables"],
  Fishing: ["FishingLures", "FishingRods"],
  OutdoorCookingAndEating: ["CampingStovesAndCookers", "CoolBoxes", "OutdoorDinnerwareAndCutlery"],
  OutdoorRecreation: ["Climbing", "HikingEquipment"],
  PunschingBagsAndSpeed: ["BagStandsAndAccessories", "BoxingPads", "PunchingBags"],
  RacketSports: ["Badminton", "Squash", "TableTennis", "Tennis"],
  ScootersAndHoverBoards: ["Hovernoards", "ScootersAndRideOns"],
  Skates: ["InlineAndRollerSkates"],
  SleepingBagsAndBedding: ["SleepingBagsAndBedding"],
  SporsProtectiveGear: ["BodyProtectors", "ElbowAndForearm", "Gaurd", "HeadGear", "MouthGuards", "ShinGaurds"],
  TentsAndCanopies: ["TentsAndCanopies"],



  WaterSportShoes: ["WaterSportShoes"],

  WaterSportsAndActivities: ["WaterSportsAndActivities"],

  AdventCalendars: ["AdventCalendars"],
  CraftSets: ["BeadAccessoriesSets", "CandlesMakingSets", "KnittingSets", "ManicureSets", "SewingSets", "SoapMakingSets"],
  DrawAndPaint: ["ColoringBooks", "ColoringClothSheets", "FacePaintsKits", "StampersAndStickers", "WashableColorPens", "WaterColorsKits"],
  PlayDoughAndClay: ["ModellingClaySets", "PlayDoughSets", "Slime"],
  SandAndMoulds: ["MagicSandSets", "SandMoulds"],

  BabyGymsAndPlaymats: ["MusicAndLightPlaymats", "PianoPlaymats", "PlayGyms", "Playments"],
  BabyToys: ["Rattles", "SoftToys", "SpiralActivityBars", "StrollerHangingToys"],
  BathToys: ['DuckBathToysSet', "SquirtBathToys", "SwimmingAnimalsAssorted", "WindUpBathToys"],
  EarlyLearning: ["ActivityCenters", "BabySoftBooks", "BusyBoards", "ColorRings", "MontessoriToys", "MusicalMobiles", "PushAndPullToys", "SoftBlocks", "StackingAndShapesSort"],
  FloorMats: ['AlphabetMats', "FoamMats", "NumberMats", "PuzzleMats", "ReversibleMats"],

  RemoteControlToys: ["RemoteControlAirplanesHelicopters", "RemoteControlAnimals", "RemoteControlVehicals", "VehiclePlaysets"],

  BuildingBlocks: ["FoamBlocks", "LegoAndBricks", "MagneticBlocks", "WoodenBlocks"],
  BuildingToys: ["ModelBuildingToys"],

  DollhousesAndAccessories: ["DollAccessories", "DollStrollers", "Dollhouses"],
  Dolls: ["BabyDolls", "FashionDolls"],

  LanguageAndLiteracy: ["AlphabetFlashcards", "KidsLaptops", "KidsTablets", "LearningBooks", "MagneticLetters", "Stories", "TimeTeachingClock"],
  MathAndCountToys: ["MagneticNumbers", "MathLearningBooks", "NumbersFlashcards", "WoodenAbacus"],
  ScienceToys: ['ScienceToys'],
  WritingBoards: ['ChalkBoards', "MagneticDrawingBoards", "WhiteBoards"],

  SoundAndLightToys: ["DancingToys", "MusicalInstruments", "MusicalPhones", "SteeringWheels", ""],

  FidgetToys: ["FidgetToys"],
  SquishyToys: ["SquishyToys"],

  BeachToys: ["BeachBalls", "Kites", "SandToolsSets"],
  BikesScootersAndRideOns: ["Bicycles", "Helmets", "RideOnCars", "Scooters", "SkateBoards", "Swayers", "Tricycles"],
  OutdoorPlay: ['BouncingCastlesAndInflatables', "PaintAndBubbleGuns", "Tents", "Trampolines"],
  PlaygroundSet: ['Seesaws', "Slides", "Swings"],
  PoolsAndWaterFun: ['Floaties', "InflatablePools", "SprinklerPads", "SwimmingRings", "WaterGuns", "WaterSlides"],


  AnimalAndActionFigures: ["ActionFigures", "AnimalFigures"],
  VehicleToys: ["Bikes", "Buses", "Cars", "Planes", "ShipsAndBoats", "Submarines", "Trains", "Trucks"],

  DressingUpAndCostumes: ["Accessories", "Costumes", "Masks", "Wigs"],
  PretendPlay: ["BeautyPlaysets", "DoctorPlaysets", "HairstylingPlaysets", "HouseholdPlaysets", "KitchenPlaysets", "ShoppingCartsPlaysets"],

  Games: ["BoardGames", "CardGames", "DartGames"],
  Puzzles: ["Puzzles3D", "BrainTeasers", "JigsawPuzzles", "PeggedPuzzles", "WoodenPuzzles"],

  BathroomAndKitchenAccessories: ["BathroomRacksAndHolders", "DrainStrainersPlugsAndCovers", "Drains", "KitchenRacksAndHolders", "ShowerFootrests", "ShwerGrabBars"],
  SinksVanitiesAndCabinets: ["BathroomCabinets", "BathroomMirrors", "BathroomsSinks", "BathroomVanities", "CabinetPartsAndAccessories", "KitchenCabinets", "kitchenSinks"],
  TapsAndFaucets: ['BathroomFaucets', "BidetFaucets", "FaucetAccessories", "KitchenFaucets"],
  ToiletsAndAccessoroies: ["BidetShattaf", "Bidets", "SquatPans", "TankFillingAndFlushing", "TankLeversAndPushButtons", "ToiletBowls", "ToiletSeatsAndCovers", "ToiletTanksAndCovers", "Toilets", "Urinals"],
  TubsAndShowers: ["BathAndShowerSystem", "Bathtubs", "SaunaRooms", "ShowerRooms", "ShowerScreensAndDoors", "ShowerSystemParts", "ShowerTrays", "ShowerheadFilters", "Showerheads", "SpaTubsAndJacuzzi"],

  BuildingBoards: ["AluminumBoards", "Cementboards", "Drywalls"],
  BuildingGlassAndAccessories: ["ClearGlass", "CurtainWallAccessories", "CurtainWalls", "DecorativeAndPatternedGlass", "ElectrochromicGlass", "InsulatedGlass", "LaminatedGlass", "ReflectiveGlass", "TemperedGlass", "TintedGlass"],
  BuldingMaterials: ['Admixtures', "Bitumen", "BricksAndStone", "Cement", "CopperRods", "GypsumPowder", "InsulationAndSoundproofingMaterial", "PatchingAndRepairMaterial", "Rebars", "RoofingTiles", "Sand", "TimberAndPlywood"],
  Ceiling: ["CeilingBeams", "CeilingTiles", "GypsumCeilingParts"],
  ElevatorsAndEscalators: ['ElevatorParts', "Elevators", "EscalatorParts", "Escalators"],
  Flooring: ["AntiStaticFlooring", "ArtificialGrass", "BambooFlooring", "CorkFlooring", "Decking", "CorkFlooring", "EngineeredFlooring", "FlooringAccessories", "laminateFlooring", "PavingStones", "PlasticFlooring", "RubberFlooring", "TileAccessories", "Tiles", "WoodFlooring"],
  HandrailsAndBalustrade: ["BalustradePartsAndAccessories", "Balustrades", "HandrailPartsAndAccessories", "Handrails"],
  LaddersAndScaffolding: ['Ladders', "ScaffoldingParts", "Scaffoldings", "TrolleysAndWheelbarrows", "WorkPlatforms"],

  DoorAndWindowHardware: ["DoorAndWindowRollerWheels", "DoorFrames", "DoorFrames", "DoorKickPlates", "DoorKnockers", "DoorViewers", "DoorPlates", "DoorBells", "DoorstopsAndClosers", "HandlesKnobsAndLever", "ScreenAndSplineAccessories", "ScreensAndSplines", "WeatherStripping"],
  Doors: ["AutomaticDoors", "FoldingDoors", "GarageDoors", "Gates", "RevolvingDoors", "SlabDoors", "SlidingDoors", "SwingDoors"],
  Windows: ['AwningWindows', "CasementWindows", "FoldingWindows", "PictureWindows", "SlidingWindows"],


  CablesWiresAndAccessories: ["CableClipsTiesAndWraps", "CableConduitsAndTrunks", "CableConduits&Trunks", "CableLadders", "ElectricalWirs", "WiringHarness"],
  FusesAndCircuitBreakers: ["ElectricalCircuitBreakers", "ElectricalCircuitBreakers"],
  PlugsAndSockets: ['AudioAndVideoWallPlates', "PowerPlugs", "PowerSockets", "SwitchedSockets"],
  PowerSupplies: ["GeneratorParts", "Generators", "InverterPartsAndAccessories", "PortablePowerStatic", "PowerPanels", "SolarPanels", "VoltageRegulators"],
  RelaysAndControllers: ["ElectricalController", "ElectricalRelays"],
  Switches: ["DipSwitches", "FlowSwitches", "InductiveSwitches", "LimitSwitches", "MicroSwitches", "PressureSwitches", "PushButtonSwitches", "RemoteControlSwitches", "RemoteControlSwitches", "RockerSwitches", "RotarySwitches", "SlideSwitches", "TemperatureControler", "TimeSwitches", "ToggleSwitches"],
  TerminalsAndConnected: ["Connectors", "Terminals"],
  UtilityBoxes: ["CableBoxes", "ElectricalBoxes"],

  AdhesivesAndFillers: ["CaulkAndSealant", "Glue", "Resin", "SiliconeTubes"],
  PaintAndCoating: ["AutomotivePaintAndCoating", "DecorativePaintAndCoating", "FlooringPaintAndCoating", "IndustrialPaintAndCoating", "MarinePaintAndCoating", "PrimersAndBaseCoats", "ProtectivePaintsAndCoating", "TopCoats", "WoodPaintsAndCoating"],
  Tapes: ["ElectricalTapes", "FloorMarkingTapes", "MountingTapes", "TapeApplicators", "TeflonTapes"],

  IndoorLighting: ["BathroomLighting", "CeilingLights", "DecorativeLights", "FloorLamps", "LightBulbs", "PictureLights", "SpotLightsAndDownlights", "TableLamps", "TrackLighting", "WallLights"],
  OutdoorLighting: ["CampingLights", "DeckLights", "EmergencyAndWarningLights", "FloodLights", "LampPosts", "SolarLights", "SpikeLights", "UnderWaterLights"],
  PortableLighting: ["Flashlights", "ReadingLights", "RingLights"],

  Alarms: ["AlarmSystems", "GlassBreakDetectors", "HeatAndSmokeDetector", "MotionDetectors"],
  ChildSafety: ["AntiSlipsANdUnderlays", "CabinetLocksAndStraps", "DoorAndWindowGuards", "EdgeAndCormerBumper", "PlugSocketCovers", "StoveGaurds", "ToiletLocks"],
  Firefighting: ["FireAlarmControlParts", "FireAlarms", "FireBlankets", "FireExtinguishers", "FireHose", "FireResistanceEquipments"],
  LocksAndKeys: ["BlankKeys", "DoorGuards", "Hasps", "LockCylinders", "LocksAndBoltsAndLatches", "Padlocks", "SmartLocks"],
  RoadwaySafty: ["ReflectiveGear", "SpeedBumps", "TrafficBarriers", "TrafficLights"],
  Surveillance: ["CctvCameras", "NetworkSecurityCameras", "LifeBuoys", "LifeRafts", "LifeVests", "RescueTools"],
  WaterSafty: ["LifeRafts", "LifeVests", "RescueTools", "LifeBuoys"],
  WorkplaceSafety: ["ConvexMirrors", "EyeProtection", "FootProtection", "Headlamps", "HearingProtection", "RespiratorsMasks", "SaftyBeltsAndStraps", "SafetyClothing", "SafetyGloves", "SafetyHelmets"],

  DimensionalAndLevelMeasurement: ["Calipers", "Micrometers", "LevelMeasurmentTools", "Micrometers", "ThicknessGauges"],
  ElectricalMeasurement: ["CurrentAndVoltageMeters", "EMFMeters", "EnergyMeters", "FrequencyCounterAndMeters", "FunctionGenerator", "PulseGenerators", "ResistanceAndCapacitanceMeters", "SpectrumAnalyzerAndOscilloscopes"],

  Fasteners: ["Bolts", "Nuts", "Flanges", "GasketsAndSeals", "Hinges", "Nails", "Nuts", "Pins", "RetainingRings", "Rivets", "ScrewEyesAndHooks", "ScrewsAnchorsAndPlugs", "Shackles", "Staples", "StudsAndThreadesRods", "ThreadsInserts", "Washers"],
  FurnitureHardware: ["CasterAndRollerWheels", "Dampers", "EdgeBanding", "FurnitureLegs", "FurniturePads", "SlidingRails"],

};

export { supOptions, subOptions, miniSubOptions, microSubOptions }

