
const countryNames = {
    USD: 'United States',
    EUR: 'European Union',
    GBP: 'United Kingdom',
    INR: 'India',
    AUD: 'Australia',
    CAD: 'Canada',
    SGD: 'Singapore',
    JPY: 'Japan',
    CNY: 'China',
    HKD: 'Hong Kong',
    NZD: 'New Zealand',
    CHF: 'Switzerland',
    SEK: 'Sweden',
    ZAR: 'South Africa',
    KRW: 'South Korea',
    TRY: 'Turkey',
    RUB: 'Russia',
    BRL: 'Brazil',
    MXN: 'Mexico',
    PLN: 'Poland',
    NOK: 'Norway',
    DKK: 'Denmark',
    PHP: 'Philippines',
    THB: 'Thailand',
    IDR: 'Indonesia',
    MYR: 'Malaysia',
    SAR: 'Saudi Arabia',
    AED: 'United Arab Emirates',
    CLP: 'Chile',
    ARS: 'Argentina',
    COP: 'Colombia',
    PEN: 'Peru',
    UAH: 'Ukraine',
    VND: 'Vietnam',
    NGN: 'Nigeria',
    IQD: 'Iraq',
    EGP: 'Egypt',
    KWD: 'Kuwait',
    PKR: 'Pakistan',
    QAR: 'Qatar',
    CRC: 'Costa Rica',
    HUF: 'Hungary',
    CZK: 'Czech Republic',
    ILS: 'Israel',
    DZD: 'Algeria',
    JOD: 'Jordan',
    MAD: 'Morocco',
    RON: 'Romania',
    UYU: 'Uruguay',
    BOB: 'Bolivia',
    BHD: 'Bahrain',
    LKR: 'Sri Lanka',
    BDT: 'Bangladesh',
    TWD: 'Taiwan',
    TZS: 'Tanzania',
    GEL: 'Georgia',
    BYN: 'Belarus',
    XAF: 'Central African Republic',
    XOF: 'Benin',
    AFN: 'Afghanistan',
    ALL: 'Albania',
    AMD: 'Armenia',
    ANG: 'Netherlands Antilles',
    AOA: 'Angola',
    AWG: 'Aruba',
    AZN: 'Azerbaijan',
    BAM: 'Bosnia and Herzegovina',
    BBD: 'Barbados',
    BGN: 'Bulgaria',
    BIF: 'Burundi',
    BMD: 'Bermuda',
    BND: 'Brunei',
    BSD: 'Bahamas',
    BTN: 'Bhutan',
    BWP: 'Botswana',
    BZD: 'Belize',
    CDF: 'Democratic Republic of the Congo',
    CUP: 'Cuba',
    CVE: 'Cape Verde',
    DJF: 'Djibouti',
    DOP: 'Dominican Republic',
    ERN: 'Eritrea',
    ETB: 'Ethiopia',
    FJD: 'Fiji',
    FKP: 'Falkland Islands',
    FOK: 'Faroe Islands',
    GGP: 'Guernsey',
    GHS: 'Ghana',
    GIP: 'Gibraltar',
    GMD: 'Gambia',
    GNF: 'Guinea',
    GTQ: 'Guatemala',
    GYD: 'Guyana',
    HNL: 'Honduras',
    HRK: 'Croatia',
    HTG: 'Haiti',
    IMP: 'Isle of Man',
    IRR: 'Iran',
    ISK: 'Iceland',
    JEP: 'Jersey',
    JMD: 'Jamaica',
    KES: 'Kenya',
    KGS: 'Kyrgyzstan',
    KHR: 'Cambodia',
    KID: 'Kiribati',
    KMF: 'Comoros',
    KYD: 'Cayman Islands',
    KZT: 'Kazakhstan',
    LAK: 'Laos',
    LBP: 'Lebanon',
    LRD: 'Liberia',
    LSL: 'Lesotho',
    LYD: 'Libya',
    MDL: 'Moldova',
    MGA: 'Madagascar',
    MKD: 'Macedonia',
    MMK: 'Myanmar',
    MNT: 'Mongolia',
    MOP: 'Macau',
    MRU: 'Mauritania',
    MUR: 'Mauritius',
    MVR: 'Maldives',
    MWK: 'Malawi',
    MZN: 'Mozambique',
    NAD: 'Namibia',
    NIO: 'Nicaragua',
    NPR: 'Nepal',
    OMR: 'Oman',
    PAB: 'Panama',
    PGK: 'Papua New Guinea',
    PYG: 'Paraguay',
    RSD: 'Serbia',
    RWF: 'Rwanda',
    SBD: 'Solomon Islands',
    SCR: 'Seychelles',
    SDG: 'Sudan',
    SHP: 'Saint Helena',
    SLE: 'Sierra Leone',
    SOS: 'Somalia',
    SRD: 'Suriname',
    SSP: 'South Sudan',
    STN: 'São Tomé and Príncipe',
    SYP: 'Syria',
    SZL: 'Swaziland',
    TJS: 'Tajikistan',
    TMT: 'Turkmenistan',
    TND: 'Tunisia',
    TOP: 'Tonga',
    TTD: 'Trinidad and Tobago',
    TVD: 'Tuvalu',
    UGX: 'Uganda',
    UZS: 'Uzbekistan',
    VES: 'Venezuela',
    VUV: 'Vanuatu',
    WST: 'Samoa',
    XCD: 'East Caribbean Dollar',
    XDR: 'International Monetary Fund',
    XPF: 'French Polynesia',
    YER: 'Yemen',
    ZMW: 'Zambia',
    ZWL: 'Zimbabwe',
    SLL: 'Sierra Leonean leone',
};

export default countryNames;